	 (:action share_alice_bob_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(Balice_secret_bob)
		)
	    :effect (and
            (when (and (at_bob_l1)) (Bbob_secret_bob))
			(when (and (at_bob_l1)) (PBbob_secret_bob))
			(when (and (at_bob_l1)) (not (Bbob_not_secret_bob)))
			(when (and (at_bob_l1)) (not (PBbob_not_secret_bob)))

            (when (and (at_alice_l1)) (Balice_secret_bob))
			(when (and (at_alice_l1)) (PBalice_secret_bob))
			(when (and (at_alice_l1)) (not (PBalice_not_secret_bob)))
			(when (and (at_alice_l1)) (not (Balice_not_secret_bob)))

            (when (and (at_alice_l1) (at_bob_l1)) (Bbob_Balice_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBalice_PBbob_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (Bbob_PBalice_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (PBbob_Balice_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (Balice_Bbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (Balice_PBbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBbob_PBalice_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (PBbob_PBalice_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (PBalice_Bbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (Bbob_PBalice_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (PBalice_PBbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (Balice_PBbob_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBalice_Bbob_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (not (Balice_Bbob_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (not (Bbob_Balice_not_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBbob_Balice_not_secret_bob)))
		)
     )