(define (problem grapevine-prob)

    (:domain grapevine)

    (:init
        (Ba_secret_a)
        (Bb_secret_b)
        (Pa_not_secret_b)
        (Pa_Ba_not_secret_a)
        (Pa_Ba_not_secret_b)
        (Pa_Ba_secret_a)
        (Pa_Ba_secret_b)
        (Pa_Bb_not_secret_a)
        (Pa_Bb_not_secret_b)
        (Pa_Bb_secret_a)
        (Pa_Bb_secret_b)
        (Pa_Pa_not_secret_a)
        (Pa_Pa_not_secret_b)
        (Pa_Pa_secret_a)
        (Pa_Pa_secret_b)
        (Pa_Pb_not_secret_a)
        (Pa_Pb_not_secret_b)
        (Pa_Pb_secret_a)
        (Pa_Pb_secret_b)
        (Pa_secret_a)
        (Pa_secret_b)
        (Pb_not_secret_a)
        (Pb_Ba_not_secret_a)
        (Pb_Ba_not_secret_b)
        (Pb_Ba_secret_a)
        (Pb_Ba_secret_b)
        (Pb_Bb_not_secret_a)
        (Pb_Bb_not_secret_b)
        (Pb_Bb_secret_a)
        (Pb_Bb_secret_b)
        (Pb_Pa_not_secret_a)
        (Pb_Pa_not_secret_b)
        (Pb_Pa_secret_a)
        (Pb_Pa_secret_b)
        (Pb_Pb_not_secret_a)
        (Pb_Pb_not_secret_b)
        (Pb_Pb_secret_a)
        (Pb_Pb_secret_b)
        (Pb_secret_a)
        (Pb_secret_b)
        (at_a_l1)
        (at_b_l2)
        (connected_l1_l2)
        (connected_l2_l1)
    )

    (:goal (and
        (Ba_secret_b)
        (Pa_secret_b)
    ))
)