(define (problem grapevine)
	(:domain grapevine)
	(:requirements :typing)
	(:objects l1 l2 - loc)
	(:init 
		(PBELbob_PBELalice_secret_bob)
		(PBELbob_BELbob_secret_alice)
		(PBELbob_PBELbob_secret_alice)
		(PBELbob_BELalice_secret_bob)
		(PBELalice_BELalice_secret_alice)
		(PBELbob_BELalice_not_secret_bob)
		(PBELalice_BELalice_not_secret_bob)
		(PBELbob_secret_bob)
		(PBELbob_PBELalice_not_secret_bob)
		(at_alice_l1)
		(PBELalice_secret_alice)
		(BELalice_secret_alice)
		(PBELalice_not_secret_bob)
		(PBELalice_BELbob_secret_alice)
		(PBELbob_PBELbob_not_secret_alice)
		(PBELalice_PBELalice_secret_alice)
		(PBELbob_secret_alice)
		(PBELalice_PBELalice_not_secret_bob)
		(PBELbob_BELalice_secret_alice)
		(connected_l2_l1)
		(PBELbob_PBELalice_not_secret_alice)
		(PBELbob_BELalice_not_secret_alice)
		(PBELalice_PBELalice_not_secret_alice)
		(PBELalice_PBELbob_secret_bob)
		(PBELalice_BELbob_not_secret_bob)
		(PBELbob_PBELalice_secret_alice)
		(BELbob_secret_bob)
		(PBELalice_BELalice_not_secret_alice)
		(at_bob_l2)
		(PBELbob_PBELbob_secret_bob)
		(PBELalice_BELalice_secret_bob)
		(PBELalice_PBELbob_secret_alice)
		(PBELbob_BELbob_not_secret_bob)
		(PBELbob_not_secret_alice)
		(PBELalice_PBELbob_not_secret_bob)
		(PBELalice_secret_bob)
		(PBELalice_BELbob_not_secret_alice)
		(PBELalice_PBELalice_secret_bob)
		(PBELbob_BELbob_secret_bob)
		(PBELbob_PBELbob_not_secret_bob)
		(connected_l1_l2)
		(PBELalice_BELbob_secret_bob)
		(PBELbob_BELbob_not_secret_alice)
		(PBELalice_PBELbob_not_secret_alice)
	)
	(:goal (and (BELalice_secret_bob)))
)