(define (domain grapevine)
	(:requirements :typing)
	(:types
	    agent loc
	)
	(:predicates
		(PBELbob_PBELalice_secret_bob)
		(BELbob_BELbob_secret_bob)
		(PBELbob_PBELbob_secret_alice)
		(PBELalice_BELalice_secret_alice)
		(PBELalice_BELalice_not_secret_bob)
		(at_bob_l1)
		(BELbob_secret_alice)
		(PBELalice_secret_alice)
		(PBELalice_not_secret_bob)
		(BELbob_PBELalice_not_secret_bob)
		(at_bob_l2)
		(PBELbob_secret_alice)
		(BELalice_secret_bob)
		(BELbob_BELalice_not_secret_bob)
		(BELalice_not_secret_bob)
		(connected_l2_l1)
		(PBELbob_BELalice_not_secret_alice)
		(PBELalice_PBELalice_not_secret_alice)
		(PBELbob_not_secret_bob)
		(PBELalice_BELalice_not_secret_alice)
		(BELbob_BELbob_not_secret_bob)
		(BELalice_secret_alice)
		(PBELalice_BELalice_secret_bob)
		(BELbob_PBELalice_not_secret_alice)
		(PBELbob_BELbob_not_secret_bob)
		(PBELalice_secret_bob)
		(BELalice_BELalice_not_secret_bob)
		(PBELalice_BELbob_not_secret_alice)
		(PBELalice_PBELalice_secret_bob)
		(PBELbob_BELbob_secret_bob)
		(BELbob_PBELbob_not_secret_bob)
		(connected_l2_l2)
		(BELalice_not_secret_alice)
		(BELalice_PBELalice_not_secret_alice)
		(PBELalice_BELbob_secret_bob)
		(BELbob_BELalice_secret_bob)
		(PBELbob_BELbob_not_secret_alice)
		(BELbob_secret_bob)
		(BELalice_BELalice_not_secret_alice)
		(BELbob_BELbob_not_secret_alice)
		(BELbob_PBELalice_secret_bob)
		(PBELbob_BELbob_secret_alice)
		(PBELbob_BELalice_secret_bob)
		(connected_l1_l2)
		(PBELbob_BELalice_not_secret_bob)
		(BELbob_PBELbob_not_secret_alice)
		(PBELbob_secret_bob)
		(PBELbob_PBELalice_not_secret_bob)
		(PBELalice_BELbob_secret_alice)
		(BELbob_BELalice_secret_alice)
		(PBELbob_PBELbob_not_secret_alice)
		(PBELalice_PBELalice_secret_alice)
		(BELbob_not_secret_bob)
		(BELalice_PBELbob_secret_bob)
		(PBELalice_PBELalice_not_secret_bob)
		(BELalice_BELbob_not_secret_bob)
		(BELbob_PBELalice_secret_alice)
		(PBELbob_BELalice_secret_alice)
		(secret_alice)
		(BELalice_BELbob_secret_bob)
		(PBELbob_PBELalice_not_secret_alice)
		(PBELalice_PBELbob_secret_bob)
		(PBELalice_BELbob_not_secret_bob)
		(PBELbob_PBELalice_secret_alice)
		(BELalice_PBELalice_secret_bob)
		(BELbob_BELbob_secret_alice)
		(BELbob_PBELbob_secret_bob)
		(at_alice_l2)
		(BELbob_not_secret_alice)
		(BELalice_PBELbob_secret_alice)
		(BELalice_PBELbob_not_secret_bob)
		(PBELalice_not_secret_alice)
		(PBELbob_PBELbob_secret_bob)
		(not_secret_bob)
		(BELalice_BELalice_secret_bob)
		(PBELalice_PBELbob_secret_alice)
		(BELbob_BELalice_not_secret_alice)
		(PBELbob_not_secret_alice)
		(PBELalice_PBELbob_not_secret_bob)
		(BELalice_PBELalice_secret_alice)
		(BELalice_PBELalice_not_secret_bob)
		(BELalice_BELbob_not_secret_alice)
		(PBELbob_PBELbob_not_secret_bob)
		(BELalice_PBELbob_not_secret_alice)
		(BELalice_BELbob_secret_alice)
		(not_secret_alice)
		(BELbob_PBELbob_secret_alice)
		(BELalice_BELalice_secret_alice)
		(connected_l1_l1)
		(at_alice_l1)
		(PBELalice_PBELbob_not_secret_alice)
		(secret_bob)
	)
	(:action move_alice_l1_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l1_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(not (at_alice_l1))
			(at_alice_l2)
		)
	)
	 (:action move_alice_l2_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(not (at_alice_l2))
			(at_alice_l1)
		)
	)
	 (:action move_alice_l2_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(not (at_alice_l2))
			(at_alice_l2)
		)
	)
	 (:action move_bob_l1_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l1_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l2_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l2))
		)
	)
	 (:action move_bob_l2_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l2))
		)
	)
	 (:action share_alice_alice_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BELalice_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l1) (at_bob_l1)) (BELalice_DISbob_secret_alice)); mutual-awareness-pos__belief id(89190ea2) / parent(134eabf6)
			(when (and (at_bob_l1)) (not (BELbob_PDISbob_not_secret_alice))); negation-removal id(6e9c8a46) / parent(857c289e)
			(when (and (at_alice_l1)) (PBELalice_DISalice_secret_alice)); mutual-awareness-neg__belief id(448ebaf4) / parent(ddc7cf6e)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELbob_DISalice_secret_alice)); mutual-awareness-neg__belief id(ee58e50a) / parent(ddc7cf6e)
			(when (and (at_alice_l1)) (DISalice_secret_alice))
			(when (and (at_bob_l1)) (not (PBELbob_PDISbob_not_secret_alice))); negation-removal id(99491f33) / parent(deaabd79)
			(when (and (at_bob_l1)) (BELbob_DISbob_secret_alice)); mutual-awareness-pos__belief id(deaabd79) / parent(134eabf6)
			(when (and (at_alice_l1)) (BELalice_DISalice_secret_alice)); mutual-awareness-pos__belief id(df7997a0) / parent(e17efad5)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELalice_DISbob_secret_alice)); mutual-awareness-neg__belief id(a1c25973) / parent(0c10475c)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELbob_PDISalice_not_secret_alice))); negation-removal id(92b86c75) / parent(ee58e50a)
			(when (and (at_alice_l1)) (not (PDISalice_not_secret_alice))); negation-removal id(ddc7cf6e) / parent(e17efad5)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELalice_PDISbob_not_secret_alice))); negation-removal id(908aec26) / parent(a1c25973)
			(when (and (at_bob_l1)) (DISbob_secret_alice))
			(when (and (at_bob_l1)) (PBELbob_DISbob_secret_alice)); mutual-awareness-neg__belief id(857c289e) / parent(0c10475c)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELalice_PDISbob_not_secret_alice))); negation-removal id(e9216a28) / parent(89190ea2)
			(when (and (at_alice_l1)) (not (PBELalice_PDISalice_not_secret_alice))); negation-removal id(3e274f64) / parent(df7997a0)
			(when (and (at_alice_l1)) (not (BELalice_PDISalice_not_secret_alice))); negation-removal id(5b2323e0) / parent(448ebaf4)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELbob_PDISalice_not_secret_alice))); negation-removal id(670c4e02) / parent(fb01375e)
			(when (and (at_alice_l1) (at_bob_l1)) (BELbob_DISalice_secret_alice)); mutual-awareness-pos__belief id(fb01375e) / parent(e17efad5)
			(when (and (at_bob_l1)) (not (PDISbob_not_secret_alice))); negation-removal id(0c10475c) / parent(134eabf6)
		)
	)
	 (:action share_alice_alice_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BELalice_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (not (PBELbob_PDISbob_not_secret_alice))); negation-removal id(f0153cb0) / parent(5b659483)
			(when (and (at_bob_l2)) (BELbob_DISbob_secret_alice)); mutual-awareness-pos__belief id(5b659483) / parent(1148aeeb)
			(when (and (at_alice_l2) (at_bob_l2)) (PBELbob_DISalice_secret_alice)); mutual-awareness-neg__belief id(c4420fa3) / parent(54147647)
			(when (and (at_alice_l2)) (PBELalice_DISalice_secret_alice)); mutual-awareness-neg__belief id(3f990ee9) / parent(54147647)
			(when (and (at_alice_l2)) (DISalice_secret_alice))
			(when (and (at_alice_l2) (at_bob_l2)) (PBELalice_DISbob_secret_alice)); mutual-awareness-neg__belief id(558488bf) / parent(7ecd4b4b)
			(when (and (at_alice_l2)) (BELalice_DISalice_secret_alice)); mutual-awareness-pos__belief id(46d30981) / parent(f219883b)
			(when (and (at_bob_l2)) (DISbob_secret_alice))
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELbob_PDISalice_not_secret_alice))); negation-removal id(5d5e5e4d) / parent(c4420fa3)
			(when (and (at_bob_l2)) (PBELbob_DISbob_secret_alice)); mutual-awareness-neg__belief id(6ecf4d83) / parent(7ecd4b4b)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELalice_PDISbob_not_secret_alice))); negation-removal id(9f61b8f4) / parent(558488bf)
			(when (and (at_alice_l2)) (not (PDISalice_not_secret_alice))); negation-removal id(54147647) / parent(f219883b)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELalice_PDISbob_not_secret_alice))); negation-removal id(6ae47640) / parent(259453a1)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELbob_PDISalice_not_secret_alice))); negation-removal id(627843e5) / parent(8a4d0ce7)
			(when (and (at_bob_l2)) (not (PDISbob_not_secret_alice))); negation-removal id(7ecd4b4b) / parent(1148aeeb)
			(when (and (at_bob_l2)) (not (BELbob_PDISbob_not_secret_alice))); negation-removal id(81f65cc8) / parent(6ecf4d83)
			(when (and (at_alice_l2) (at_bob_l2)) (BELbob_DISalice_secret_alice)); mutual-awareness-pos__belief id(8a4d0ce7) / parent(f219883b)
			(when (and (at_alice_l2)) (not (PBELalice_PDISalice_not_secret_alice))); negation-removal id(88985515) / parent(46d30981)
			(when (and (at_alice_l2)) (not (BELalice_PDISalice_not_secret_alice))); negation-removal id(692210f0) / parent(3f990ee9)
			(when (and (at_alice_l2) (at_bob_l2)) (BELalice_DISbob_secret_alice)); mutual-awareness-pos__belief id(259453a1) / parent(1148aeeb)
		)
	)
	 (:action share_alice_bob_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BELalice_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l1) (at_bob_l1)) (PBELalice_DISbob_secret_bob)); mutual-awareness-neg__belief id(3d7081ad) / parent(a946a71b)
			(when (and (at_alice_l1) (at_bob_l1)) (BELalice_DISbob_secret_bob)); mutual-awareness-pos__belief id(1605e0e6) / parent(10963891)
			(when (and (at_alice_l1)) (PBELalice_DISalice_secret_bob)); mutual-awareness-neg__belief id(38702778) / parent(128458a8)
			(when (and (at_alice_l1)) (not (PDISalice_not_secret_bob))); negation-removal id(128458a8) / parent(3c7a2c40)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELbob_PDISalice_not_secret_bob))); negation-removal id(db327744) / parent(3c8ecde0)
			(when (and (at_bob_l1)) (BELbob_DISbob_secret_bob)); mutual-awareness-pos__belief id(e92ac5f1) / parent(10963891)
			(when (and (at_bob_l1)) (PBELbob_DISbob_secret_bob)); mutual-awareness-neg__belief id(7b4c155c) / parent(a946a71b)
			(when (and (at_bob_l1)) (DISbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELbob_PDISalice_not_secret_bob))); negation-removal id(372ffc42) / parent(03a90a05)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELalice_PDISbob_not_secret_bob))); negation-removal id(55eada63) / parent(3d7081ad)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELalice_PDISbob_not_secret_bob))); negation-removal id(05773e18) / parent(1605e0e6)
			(when (and (at_alice_l1)) (not (PBELalice_PDISalice_not_secret_bob))); negation-removal id(8fc6fea5) / parent(004e18dc)
			(when (and (at_alice_l1)) (not (BELalice_PDISalice_not_secret_bob))); negation-removal id(ff74aa70) / parent(38702778)
			(when (and (at_bob_l1)) (not (BELbob_PDISbob_not_secret_bob))); negation-removal id(a29c6c6f) / parent(7b4c155c)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELbob_DISalice_secret_bob)); mutual-awareness-neg__belief id(3c8ecde0) / parent(128458a8)
			(when (and (at_alice_l1)) (DISalice_secret_bob))
			(when (and (at_bob_l1)) (not (PDISbob_not_secret_bob))); negation-removal id(a946a71b) / parent(10963891)
			(when (and (at_alice_l1)) (BELalice_DISalice_secret_bob)); mutual-awareness-pos__belief id(004e18dc) / parent(3c7a2c40)
			(when (and (at_alice_l1) (at_bob_l1)) (BELbob_DISalice_secret_bob)); mutual-awareness-pos__belief id(03a90a05) / parent(3c7a2c40)
			(when (and (at_bob_l1)) (not (PBELbob_PDISbob_not_secret_bob))); negation-removal id(e267c4c4) / parent(e92ac5f1)
		)
	)
	 (:action share_alice_bob_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BELalice_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l2)) (BELalice_DISalice_secret_bob)); mutual-awareness-pos__belief id(519c2f05) / parent(fe929c83)
			(when (and (at_bob_l2)) (BELbob_DISbob_secret_bob)); mutual-awareness-pos__belief id(7cabbbf0) / parent(b28ceff8)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELbob_PDISalice_not_secret_bob))); negation-removal id(3907bb25) / parent(5cccc24b)
			(when (and (at_bob_l2)) (PBELbob_DISbob_secret_bob)); mutual-awareness-neg__belief id(a8090ecf) / parent(ec0f9cbe)
			(when (and (at_alice_l2)) (PBELalice_DISalice_secret_bob)); mutual-awareness-neg__belief id(bc7cd7ca) / parent(d36ea952)
			(when (and (at_bob_l2)) (DISbob_secret_bob))
			(when (and (at_alice_l2)) (not (PDISalice_not_secret_bob))); negation-removal id(d36ea952) / parent(fe929c83)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELbob_PDISalice_not_secret_bob))); negation-removal id(945ab042) / parent(df513cd5)
			(when (and (at_bob_l2)) (not (BELbob_PDISbob_not_secret_bob))); negation-removal id(50886af5) / parent(a8090ecf)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELalice_PDISbob_not_secret_bob))); negation-removal id(3fb0f866) / parent(51b960aa)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELalice_PDISbob_not_secret_bob))); negation-removal id(3de15517) / parent(da6b7c74)
			(when (and (at_bob_l2)) (not (PDISbob_not_secret_bob))); negation-removal id(ec0f9cbe) / parent(b28ceff8)
			(when (and (at_alice_l2)) (not (PBELalice_PDISalice_not_secret_bob))); negation-removal id(54bd627b) / parent(519c2f05)
			(when (and (at_alice_l2) (at_bob_l2)) (PBELbob_DISalice_secret_bob)); mutual-awareness-neg__belief id(5cccc24b) / parent(d36ea952)
			(when (and (at_bob_l2)) (not (PBELbob_PDISbob_not_secret_bob))); negation-removal id(37d415ac) / parent(7cabbbf0)
			(when (and (at_alice_l2)) (not (BELalice_PDISalice_not_secret_bob))); negation-removal id(c95d51b6) / parent(bc7cd7ca)
			(when (and (at_alice_l2) (at_bob_l2)) (BELbob_DISalice_secret_bob)); mutual-awareness-pos__belief id(df513cd5) / parent(fe929c83)
			(when (and (at_alice_l2)) (DISalice_secret_bob))
			(when (and (at_alice_l2) (at_bob_l2)) (PBELalice_DISbob_secret_bob)); mutual-awareness-neg__belief id(51b960aa) / parent(ec0f9cbe)
			(when (and (at_alice_l2) (at_bob_l2)) (BELalice_DISbob_secret_bob)); mutual-awareness-pos__belief id(da6b7c74) / parent(b28ceff8)
		)
	)
	 (:action share_bob_alice_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BELbob_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l1) (at_bob_l1)) (BELalice_DISbob_secret_alice)); mutual-awareness-pos__belief id(89190ea2) / parent(134eabf6)
			(when (and (at_bob_l1)) (not (BELbob_PDISbob_not_secret_alice))); negation-removal id(6e9c8a46) / parent(857c289e)
			(when (and (at_alice_l1)) (PBELalice_DISalice_secret_alice)); mutual-awareness-neg__belief id(448ebaf4) / parent(ddc7cf6e)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELbob_DISalice_secret_alice)); mutual-awareness-neg__belief id(ee58e50a) / parent(ddc7cf6e)
			(when (and (at_alice_l1)) (DISalice_secret_alice))
			(when (and (at_bob_l1)) (not (PBELbob_PDISbob_not_secret_alice))); negation-removal id(99491f33) / parent(deaabd79)
			(when (and (at_bob_l1)) (BELbob_DISbob_secret_alice)); mutual-awareness-pos__belief id(deaabd79) / parent(134eabf6)
			(when (and (at_alice_l1)) (BELalice_DISalice_secret_alice)); mutual-awareness-pos__belief id(df7997a0) / parent(e17efad5)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELalice_DISbob_secret_alice)); mutual-awareness-neg__belief id(a1c25973) / parent(0c10475c)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELbob_PDISalice_not_secret_alice))); negation-removal id(92b86c75) / parent(ee58e50a)
			(when (and (at_alice_l1)) (not (PDISalice_not_secret_alice))); negation-removal id(ddc7cf6e) / parent(e17efad5)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELalice_PDISbob_not_secret_alice))); negation-removal id(908aec26) / parent(a1c25973)
			(when (and (at_bob_l1)) (DISbob_secret_alice))
			(when (and (at_bob_l1)) (PBELbob_DISbob_secret_alice)); mutual-awareness-neg__belief id(857c289e) / parent(0c10475c)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELalice_PDISbob_not_secret_alice))); negation-removal id(e9216a28) / parent(89190ea2)
			(when (and (at_alice_l1)) (not (PBELalice_PDISalice_not_secret_alice))); negation-removal id(3e274f64) / parent(df7997a0)
			(when (and (at_alice_l1)) (not (BELalice_PDISalice_not_secret_alice))); negation-removal id(5b2323e0) / parent(448ebaf4)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELbob_PDISalice_not_secret_alice))); negation-removal id(670c4e02) / parent(fb01375e)
			(when (and (at_alice_l1) (at_bob_l1)) (BELbob_DISalice_secret_alice)); mutual-awareness-pos__belief id(fb01375e) / parent(e17efad5)
			(when (and (at_bob_l1)) (not (PDISbob_not_secret_alice))); negation-removal id(0c10475c) / parent(134eabf6)
		)
	)
	 (:action share_bob_alice_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BELbob_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (not (PBELbob_PDISbob_not_secret_alice))); negation-removal id(f0153cb0) / parent(5b659483)
			(when (and (at_bob_l2)) (BELbob_DISbob_secret_alice)); mutual-awareness-pos__belief id(5b659483) / parent(1148aeeb)
			(when (and (at_alice_l2) (at_bob_l2)) (PBELbob_DISalice_secret_alice)); mutual-awareness-neg__belief id(c4420fa3) / parent(54147647)
			(when (and (at_alice_l2)) (PBELalice_DISalice_secret_alice)); mutual-awareness-neg__belief id(3f990ee9) / parent(54147647)
			(when (and (at_alice_l2)) (DISalice_secret_alice))
			(when (and (at_alice_l2) (at_bob_l2)) (PBELalice_DISbob_secret_alice)); mutual-awareness-neg__belief id(558488bf) / parent(7ecd4b4b)
			(when (and (at_alice_l2)) (BELalice_DISalice_secret_alice)); mutual-awareness-pos__belief id(46d30981) / parent(f219883b)
			(when (and (at_bob_l2)) (DISbob_secret_alice))
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELbob_PDISalice_not_secret_alice))); negation-removal id(5d5e5e4d) / parent(c4420fa3)
			(when (and (at_bob_l2)) (PBELbob_DISbob_secret_alice)); mutual-awareness-neg__belief id(6ecf4d83) / parent(7ecd4b4b)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELalice_PDISbob_not_secret_alice))); negation-removal id(9f61b8f4) / parent(558488bf)
			(when (and (at_alice_l2)) (not (PDISalice_not_secret_alice))); negation-removal id(54147647) / parent(f219883b)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELalice_PDISbob_not_secret_alice))); negation-removal id(6ae47640) / parent(259453a1)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELbob_PDISalice_not_secret_alice))); negation-removal id(627843e5) / parent(8a4d0ce7)
			(when (and (at_bob_l2)) (not (PDISbob_not_secret_alice))); negation-removal id(7ecd4b4b) / parent(1148aeeb)
			(when (and (at_bob_l2)) (not (BELbob_PDISbob_not_secret_alice))); negation-removal id(81f65cc8) / parent(6ecf4d83)
			(when (and (at_alice_l2) (at_bob_l2)) (BELbob_DISalice_secret_alice)); mutual-awareness-pos__belief id(8a4d0ce7) / parent(f219883b)
			(when (and (at_alice_l2)) (not (PBELalice_PDISalice_not_secret_alice))); negation-removal id(88985515) / parent(46d30981)
			(when (and (at_alice_l2)) (not (BELalice_PDISalice_not_secret_alice))); negation-removal id(692210f0) / parent(3f990ee9)
			(when (and (at_alice_l2) (at_bob_l2)) (BELalice_DISbob_secret_alice)); mutual-awareness-pos__belief id(259453a1) / parent(1148aeeb)
		)
	)
	 (:action share_bob_bob_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BELbob_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l1) (at_bob_l1)) (PBELalice_DISbob_secret_bob)); mutual-awareness-neg__belief id(3d7081ad) / parent(a946a71b)
			(when (and (at_alice_l1) (at_bob_l1)) (BELalice_DISbob_secret_bob)); mutual-awareness-pos__belief id(1605e0e6) / parent(10963891)
			(when (and (at_alice_l1)) (PBELalice_DISalice_secret_bob)); mutual-awareness-neg__belief id(38702778) / parent(128458a8)
			(when (and (at_alice_l1)) (not (PDISalice_not_secret_bob))); negation-removal id(128458a8) / parent(3c7a2c40)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELbob_PDISalice_not_secret_bob))); negation-removal id(db327744) / parent(3c8ecde0)
			(when (and (at_bob_l1)) (BELbob_DISbob_secret_bob)); mutual-awareness-pos__belief id(e92ac5f1) / parent(10963891)
			(when (and (at_bob_l1)) (PBELbob_DISbob_secret_bob)); mutual-awareness-neg__belief id(7b4c155c) / parent(a946a71b)
			(when (and (at_bob_l1)) (DISbob_secret_bob))
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELbob_PDISalice_not_secret_bob))); negation-removal id(372ffc42) / parent(03a90a05)
			(when (and (at_alice_l1) (at_bob_l1)) (not (BELalice_PDISbob_not_secret_bob))); negation-removal id(55eada63) / parent(3d7081ad)
			(when (and (at_alice_l1) (at_bob_l1)) (not (PBELalice_PDISbob_not_secret_bob))); negation-removal id(05773e18) / parent(1605e0e6)
			(when (and (at_alice_l1)) (not (PBELalice_PDISalice_not_secret_bob))); negation-removal id(8fc6fea5) / parent(004e18dc)
			(when (and (at_alice_l1)) (not (BELalice_PDISalice_not_secret_bob))); negation-removal id(ff74aa70) / parent(38702778)
			(when (and (at_bob_l1)) (not (BELbob_PDISbob_not_secret_bob))); negation-removal id(a29c6c6f) / parent(7b4c155c)
			(when (and (at_alice_l1) (at_bob_l1)) (PBELbob_DISalice_secret_bob)); mutual-awareness-neg__belief id(3c8ecde0) / parent(128458a8)
			(when (and (at_alice_l1)) (DISalice_secret_bob))
			(when (and (at_bob_l1)) (not (PDISbob_not_secret_bob))); negation-removal id(a946a71b) / parent(10963891)
			(when (and (at_alice_l1)) (BELalice_DISalice_secret_bob)); mutual-awareness-pos__belief id(004e18dc) / parent(3c7a2c40)
			(when (and (at_alice_l1) (at_bob_l1)) (BELbob_DISalice_secret_bob)); mutual-awareness-pos__belief id(03a90a05) / parent(3c7a2c40)
			(when (and (at_bob_l1)) (not (PBELbob_PDISbob_not_secret_bob))); negation-removal id(e267c4c4) / parent(e92ac5f1)
		)
	)
	 (:action share_bob_bob_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BELbob_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l2)) (BELalice_DISalice_secret_bob)); mutual-awareness-pos__belief id(519c2f05) / parent(fe929c83)
			(when (and (at_bob_l2)) (BELbob_DISbob_secret_bob)); mutual-awareness-pos__belief id(7cabbbf0) / parent(b28ceff8)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELbob_PDISalice_not_secret_bob))); negation-removal id(3907bb25) / parent(5cccc24b)
			(when (and (at_bob_l2)) (PBELbob_DISbob_secret_bob)); mutual-awareness-neg__belief id(a8090ecf) / parent(ec0f9cbe)
			(when (and (at_alice_l2)) (PBELalice_DISalice_secret_bob)); mutual-awareness-neg__belief id(bc7cd7ca) / parent(d36ea952)
			(when (and (at_bob_l2)) (DISbob_secret_bob))
			(when (and (at_alice_l2)) (not (PDISalice_not_secret_bob))); negation-removal id(d36ea952) / parent(fe929c83)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELbob_PDISalice_not_secret_bob))); negation-removal id(945ab042) / parent(df513cd5)
			(when (and (at_bob_l2)) (not (BELbob_PDISbob_not_secret_bob))); negation-removal id(50886af5) / parent(a8090ecf)
			(when (and (at_alice_l2) (at_bob_l2)) (not (BELalice_PDISbob_not_secret_bob))); negation-removal id(3fb0f866) / parent(51b960aa)
			(when (and (at_alice_l2) (at_bob_l2)) (not (PBELalice_PDISbob_not_secret_bob))); negation-removal id(3de15517) / parent(da6b7c74)
			(when (and (at_bob_l2)) (not (PDISbob_not_secret_bob))); negation-removal id(ec0f9cbe) / parent(b28ceff8)
			(when (and (at_alice_l2)) (not (PBELalice_PDISalice_not_secret_bob))); negation-removal id(54bd627b) / parent(519c2f05)
			(when (and (at_alice_l2) (at_bob_l2)) (PBELbob_DISalice_secret_bob)); mutual-awareness-neg__belief id(5cccc24b) / parent(d36ea952)
			(when (and (at_bob_l2)) (not (PBELbob_PDISbob_not_secret_bob))); negation-removal id(37d415ac) / parent(7cabbbf0)
			(when (and (at_alice_l2)) (not (BELalice_PDISalice_not_secret_bob))); negation-removal id(c95d51b6) / parent(bc7cd7ca)
			(when (and (at_alice_l2) (at_bob_l2)) (BELbob_DISalice_secret_bob)); mutual-awareness-pos__belief id(df513cd5) / parent(fe929c83)
			(when (and (at_alice_l2)) (DISalice_secret_bob))
			(when (and (at_alice_l2) (at_bob_l2)) (PBELalice_DISbob_secret_bob)); mutual-awareness-neg__belief id(51b960aa) / parent(ec0f9cbe)
			(when (and (at_alice_l2) (at_bob_l2)) (BELalice_DISbob_secret_bob)); mutual-awareness-pos__belief id(da6b7c74) / parent(b28ceff8)
		)
	)
)