
(define (problem witch-collect-item)
    (:domain suspicious_witches)
    (:objects eye_of_newt toe_of_frog - item l1 l2 l3 - loc)
    (:depth 2)
    (:task valid_assessment)
    (:init-type complete)
    (:init !<cindy>(witch bob) (at alice l1) (at bob l2) (at cindy l1) (at derek l2) (at evelyn l3) (civilian alice) (civilian cindy) (connected l1 l2) (connected l2 l1) (connected l2 l3) (connected l3 l2) (diff alice bob) (diff alice cindy) (diff bob alice) (diff bob cindy) (diff cindy alice) (diff cindy bob) (item-at eye_of_newt l1) (item-at toe_of_frog l3) (witch bob) <alice>(witch bob))
    (:goal (and (collected eye_of_newt) [alice](witch bob) <cindy>(witch bob)))
    (:plan (collect-item bob eye_of_newt l1) (move bob l2 l1))
)
