(define (problem grapevine-prob)

    (:domain grapevine)

    (:init
        (Balice_secret_alice)
        (Bbob_secret_bob)
        (Palice_not_secret_bob)
        (Palice_Balice_not_secret_alice)
        (Palice_Balice_not_secret_bob)
        (Palice_Balice_secret_alice)
        (Palice_Balice_secret_bob)
        (Palice_Bbob_not_secret_alice)
        (Palice_Bbob_not_secret_bob)
        (Palice_Bbob_secret_alice)
        (Palice_Bbob_secret_bob)
        (Palice_Palice_not_secret_alice)
        (Palice_Palice_not_secret_bob)
        (Palice_Palice_secret_alice)
        (Palice_Palice_secret_bob)
        (Palice_Pbob_not_secret_alice)
        (Palice_Pbob_not_secret_bob)
        (Palice_Pbob_secret_alice)
        (Palice_Pbob_secret_bob)
        (Palice_secret_alice)
        (Palice_secret_bob)
        (Pbob_not_secret_alice)
        (Pbob_Balice_not_secret_alice)
        (Pbob_Balice_not_secret_bob)
        (Pbob_Balice_secret_alice)
        (Pbob_Balice_secret_bob)
        (Pbob_Bbob_not_secret_alice)
        (Pbob_Bbob_not_secret_bob)
        (Pbob_Bbob_secret_alice)
        (Pbob_Bbob_secret_bob)
        (Pbob_Palice_not_secret_alice)
        (Pbob_Palice_not_secret_bob)
        (Pbob_Palice_secret_alice)
        (Pbob_Palice_secret_bob)
        (Pbob_Pbob_not_secret_alice)
        (Pbob_Pbob_not_secret_bob)
        (Pbob_Pbob_secret_alice)
        (Pbob_Pbob_secret_bob)
        (Pbob_secret_alice)
        (Pbob_secret_bob)
        (at_alice_l1)
        (at_bob_l2)
        (connected_l1_l2)
        (connected_l2_l1)
    )

    (:goal (and
        (Balice_secret_bob)
        (Palice_secret_bob)
    ))
)