(define (domain bdi)
	(:requirements :typing)
	(:agents a b)
	(:types
	    agent loc
	)
	(:predicates
		(Ba_Bb_not_secret_a)
		(Ba_PBb_not_secret_b)
		(Bb_PBb_not_secret_b)
		(connected_l2_l1)
		(PBb_Ba_not_secret_a)
		(Bb_not_secret_a)
		(PBa_secret_a)
		(PBa_Ba_not_secret_b)
		(Ba_Bb_secret_b)
		(secret_b)
		(Bb_PBa_secret_a)
		(not_connected_l1_l1)
		(PBb_secret_a)
		(PBb_Ba_not_secret_b)
		(PBb_PBb_not_secret_a)
		(not_connected_l1_l2)
		(PBa_Bb_secret_a)
		(PBb_not_secret_a)
		(Ba_PBa_secret_b)
		(PBa_PBb_not_secret_b)
		(at_a_l1)
		(PBa_PBa_not_secret_a)
		(Bb_PBa_secret_b)
		(not_at_b_l1)
		(Ba_Ba_secret_a)
		(PBa_PBa_secret_b)
		(not_at_a_l2)
		(Bb_Bb_not_secret_a)
		(PBa_Bb_not_secret_a)
		(connected_l1_l2)
		(Ba_PBa_not_secret_b)
		(PBb_PBb_not_secret_b)
		(Ba_Ba_not_secret_a)
		(PBa_secret_b)
		(PBb_PBb_secret_a)
		(PBa_Ba_secret_a)
		(PBb_Bb_not_secret_a)
		(Bb_Bb_secret_b)
		(Bb_Ba_secret_a)
		(PBb_PBa_secret_a)
		(Bb_PBb_not_secret_a)
		(not_secret_a)
		(PBa_not_secret_b)
		(Bb_PBb_secret_b)
		(Bb_Bb_not_secret_b)
		(at_b_l2)
		(PBb_not_secret_b)
		(PBb_Bb_secret_b)
		(Ba_Bb_secret_a)
		(Ba_secret_a)
		(Ba_Ba_not_secret_b)
		(PBb_PBb_secret_b)
		(PBa_Ba_secret_b)
		(Ba_PBb_not_secret_a)
		(secret_a)
		(not_secret_b)
		(not_connected_l2_l1)
		(PBa_Bb_not_secret_b)
		(at_b_l1)
		(Ba_PBa_secret_a)
		(connected_l2_l2)
		(Ba_secret_b)
		(PBb_Ba_secret_a)
		(PBa_PBb_not_secret_a)
		(not_at_a_l1)
		(PBa_PBa_secret_a)
		(Ba_not_secret_b)
		(PBb_PBa_not_secret_b)
		(Ba_PBa_not_secret_a)
		(PBa_not_secret_a)
		(Bb_secret_a)
		(Bb_Ba_not_secret_b)
		(PBb_Ba_secret_b)
		(Bb_PBb_secret_a)
		(Bb_PBa_not_secret_a)
		(Ba_PBb_secret_b)
		(PBb_Bb_secret_a)
		(Ba_Bb_not_secret_b)
		(Bb_Bb_secret_a)
		(Bb_not_secret_b)
		(Bb_secret_b)
		(PBa_PBb_secret_a)
		(PBa_PBb_secret_b)
		(Bb_PBa_not_secret_b)
		(connected_l1_l1)
		(not_at_b_l2)
		(PBb_secret_b)
		(PBa_Bb_secret_b)
		(not_connected_l2_l2)
		(Ba_not_secret_a)
		(PBb_PBa_not_secret_a)
		(PBa_PBa_not_secret_b)
		(at_a_l2)
		(Ba_Ba_secret_b)
		(Bb_Ba_not_secret_a)
		(PBa_Ba_not_secret_a)
		(Bb_Ba_secret_b)
		(PBb_PBa_secret_b)
		(PBb_Bb_not_secret_b)
		(Ba_PBb_secret_a)
	)
	(:action move_a_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_a_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(not (at_a_l1))
			(not_at_a_l1)
			(not (not_at_a_l1))
			(at_a_l1)
		)
	)
	 (:action move_a_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_a_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_a_l2)
			(not (at_a_l1))
			(not_at_a_l1)
			(not (not_at_a_l2))
		)
	)
	 (:action move_a_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_a_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(not (at_a_l2))
			(not_at_a_l2)
			(not (not_at_a_l1))
			(at_a_l1)
		)
	)
	 (:action move_a_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_a_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_a_l2)
			(not (at_a_l2))
			(not_at_a_l2)
			(not (not_at_a_l2))
		)
	)
	 (:action move_b_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_b_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(not (at_b_l1))
			(not_at_b_l1)
			(not (not_at_b_l1))
			(at_b_l1)
		)
	)
	 (:action move_b_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_b_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_b_l2)
			(not_at_b_l1)
			(not (at_b_l1))
			(not (not_at_b_l2))
		)
	)
	 (:action move_b_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_b_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(not (at_b_l2))
			(not (not_at_b_l1))
			(not_at_b_l2)
			(at_b_l1)
		)
	)
	 (:action move_b_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_b_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_b_l2)
			(not (at_b_l2))
			(not_at_b_l2)
			(not (not_at_b_l2))
		)
	)
	 (:action share_a_a_l1
	    :derive-condition (at$agent$l1)
	    :parameters ()
	    :precondition (and
			(at_a_l1)
			(Ba_secret_a)
		)
	    :effect (and
			(when (and (at_b_l1)) (not (Bb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_Bb_not_secret_a)))
			(when (and (not (not_at_a_l1))) (not (Ba_not_secret_a)))
			(when (and (at_a_l1)) (not (PBa_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_PBb_secret_a))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Ba_PBb_secret_a))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_PBa_secret_a))
			(when (and (not (not_at_b_l1))) (not (PBb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_Ba_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_PBb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_Ba_not_secret_a)))
			(when (and (at_b_l1)) (not (PBb_not_secret_a)))
			(when (and (at_a_l1)) (not (Ba_not_secret_a)))
			(when (and (not (not_at_b_l1))) (not (Bb_not_secret_a)))
			(when (and (at_a_l1)) (PBa_secret_a))
			(when (and (at_a_l1)) (Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_Ba_not_secret_a)))
			(when (and (at_b_l1)) (PBb_secret_a))
			(when (and (not (not_at_a_l1))) (not (PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_Bb_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (Ba_Bb_secret_a))
			(when (and (at_b_l1)) (Bb_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_Ba_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_PBa_secret_a))
		)
	)
	 (:action share_a_a_l2
	    :derive-condition (at$agent$l2)
	    :parameters ()
	    :precondition (and
			(at_a_l2)
			(Ba_secret_a)
		)
	    :effect (and
			(when (and (not (not_at_b_l2))) (not (Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_Bb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Ba_Bb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_Ba_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (Bb_PBa_secret_a))
			(when (and (not (not_at_a_l2))) (not (PBa_not_secret_a)))
			(when (and (at_a_l2)) (not (Ba_not_secret_a)))
			(when (and (at_a_l2)) (Ba_secret_a))
			(when (and (at_a_l2)) (PBa_secret_a))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_PBb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Ba_PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (PBb_PBa_secret_a))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_Bb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_Bb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_PBb_not_secret_a)))
			(when (and (at_b_l2)) (not (PBb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l2))) (not (Ba_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBb_Ba_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Bb_Ba_secret_a))
			(when (and (not (not_at_b_l2))) (not (PBb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_Ba_not_secret_a)))
			(when (and (at_b_l2)) (PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_PBb_not_secret_a)))
			(when (and (at_b_l2)) (Bb_secret_a))
			(when (and (at_a_l2)) (not (PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_Ba_not_secret_a)))
			(when (and (at_b_l2)) (not (Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_Ba_not_secret_a)))
		)
	)
	 (:action share_a_b_l1
	    :derive-condition (at$agent$l1)
	    :parameters ()
	    :precondition (and
			(at_a_l1)
			(Ba_secret_b)
		)
	    :effect (and
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_Ba_secret_b))
			(when (and (not (not_at_a_l1))) (not (Ba_not_secret_b)))
			(when (and (at_a_l1)) (not (PBa_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_Bb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (Ba_PBb_secret_b))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_PBa_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (Bb_PBa_secret_b))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_PBb_not_secret_b)))
			(when (and (not (not_at_b_l1))) (not (PBb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_PBb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_PBb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_Ba_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l1)) (not (Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_PBb_not_secret_b)))
			(when (and (at_b_l1)) (not (PBb_not_secret_b)))
			(when (and (not (not_at_b_l1))) (not (Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_Ba_not_secret_b)))
			(when (and (at_a_l1)) (PBa_secret_b))
			(when (and (at_a_l1)) (Ba_secret_b))
			(when (and (at_b_l1)) (Bb_secret_b))
			(when (and (at_b_l1)) (PBb_secret_b))
			(when (and (not (not_at_a_l1))) (not (PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_Bb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (Ba_Bb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_Ba_not_secret_b)))
			(when (and (at_b_l1)) (not (Bb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_PBb_not_secret_b)))
		)
	)
	 (:action share_a_b_l2
	    :derive-condition (at$agent$l2)
	    :parameters ()
	    :precondition (and
			(at_a_l2)
			(Ba_secret_b)
		)
	    :effect (and
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_Ba_not_secret_b)))
			(when (and (not (not_at_a_l2))) (not (PBa_not_secret_b)))
			(when (and (at_a_l2)) (not (Ba_not_secret_b)))
			(when (and (at_a_l2)) (PBa_secret_b))
			(when (and (at_a_l2)) (Ba_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBb_Ba_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Ba_PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (PBb_PBa_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Bb_PBa_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_Bb_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_Bb_not_secret_b)))
			(when (and (at_b_l2)) (not (PBb_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_PBb_not_secret_b)))
			(when (and (not (not_at_a_l2))) (not (Ba_not_secret_b)))
			(when (and (not (not_at_b_l2))) (not (PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (Bb_Ba_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_Bb_not_secret_b)))
			(when (and (at_b_l2)) (Bb_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_Ba_not_secret_b)))
			(when (and (at_b_l2)) (PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_PBa_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_PBb_not_secret_b)))
			(when (and (at_a_l2)) (not (PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_Ba_not_secret_b)))
			(when (and (at_b_l2)) (not (Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_Ba_not_secret_b)))
			(when (and (not (not_at_b_l2))) (not (Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_Bb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Ba_Bb_secret_b))
		)
	)
	 (:action share_b_a_l1
	    :derive-condition (at$agent$l1)
	    :parameters ()
	    :precondition (and
			(at_b_l1)
			(Bb_secret_a)
		)
	    :effect (and
			(when (and (at_b_l1)) (not (Bb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_Bb_not_secret_a)))
			(when (and (not (not_at_a_l1))) (not (Ba_not_secret_a)))
			(when (and (at_a_l1)) (not (PBa_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_PBb_secret_a))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Ba_PBb_secret_a))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_PBa_secret_a))
			(when (and (not (not_at_b_l1))) (not (PBb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_Ba_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_PBb_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_Ba_not_secret_a)))
			(when (and (at_b_l1)) (not (PBb_not_secret_a)))
			(when (and (at_a_l1)) (not (Ba_not_secret_a)))
			(when (and (not (not_at_b_l1))) (not (Bb_not_secret_a)))
			(when (and (at_a_l1)) (PBa_secret_a))
			(when (and (at_a_l1)) (Ba_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_Ba_not_secret_a)))
			(when (and (at_b_l1)) (PBb_secret_a))
			(when (and (not (not_at_a_l1))) (not (PBa_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_Bb_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (Ba_Bb_secret_a))
			(when (and (at_b_l1)) (Bb_secret_a))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_Ba_not_secret_a)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_PBa_secret_a))
		)
	)
	 (:action share_b_a_l2
	    :derive-condition (at$agent$l2)
	    :parameters ()
	    :precondition (and
			(at_b_l2)
			(Bb_secret_a)
		)
	    :effect (and
			(when (and (not (not_at_b_l2))) (not (Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_Bb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Ba_Bb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_Ba_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (Bb_PBa_secret_a))
			(when (and (not (not_at_a_l2))) (not (PBa_not_secret_a)))
			(when (and (at_a_l2)) (not (Ba_not_secret_a)))
			(when (and (at_a_l2)) (Ba_secret_a))
			(when (and (at_a_l2)) (PBa_secret_a))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_PBb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Ba_PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (PBb_PBa_secret_a))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_Bb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_Bb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_PBb_not_secret_a)))
			(when (and (at_b_l2)) (not (PBb_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_PBb_not_secret_a)))
			(when (and (not (not_at_a_l2))) (not (Ba_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (PBb_Ba_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (Bb_Ba_secret_a))
			(when (and (not (not_at_b_l2))) (not (PBb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_Ba_not_secret_a)))
			(when (and (at_b_l2)) (PBb_secret_a))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_PBa_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_PBb_not_secret_a)))
			(when (and (at_b_l2)) (Bb_secret_a))
			(when (and (at_a_l2)) (not (PBa_not_secret_a)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_Ba_not_secret_a)))
			(when (and (at_b_l2)) (not (Bb_not_secret_a)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_Ba_not_secret_a)))
		)
	)
	 (:action share_b_b_l1
	    :derive-condition (at$agent$l1)
	    :parameters ()
	    :precondition (and
			(at_b_l1)
			(Bb_secret_b)
		)
	    :effect (and
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_Ba_secret_b))
			(when (and (not (not_at_a_l1))) (not (Ba_not_secret_b)))
			(when (and (at_a_l1)) (not (PBa_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_Bb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (Ba_PBb_secret_b))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBb_PBa_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (Bb_PBa_secret_b))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Ba_PBb_not_secret_b)))
			(when (and (not (not_at_b_l1))) (not (PBb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_PBb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_PBb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBb_Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (Bb_Ba_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (Bb_Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l1)) (not (Ba_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (Ba_PBb_not_secret_b)))
			(when (and (at_b_l1)) (not (PBb_not_secret_b)))
			(when (and (not (not_at_b_l1))) (not (Bb_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (not (PBb_Ba_not_secret_b)))
			(when (and (at_a_l1)) (PBa_secret_b))
			(when (and (at_a_l1)) (Ba_secret_b))
			(when (and (at_b_l1)) (Bb_secret_b))
			(when (and (at_b_l1)) (PBb_secret_b))
			(when (and (not (not_at_a_l1))) (not (PBa_not_secret_b)))
			(when (and (at_a_l1) (at_b_l1)) (PBa_Bb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (Ba_Bb_secret_b))
			(when (and (at_a_l1) (at_b_l1)) (not (Bb_Ba_not_secret_b)))
			(when (and (at_b_l1)) (not (Bb_not_secret_b)))
			(when (and (not (not_at_a_l1)) (not (not_at_b_l1))) (not (PBa_PBb_not_secret_b)))
		)
	)
	 (:action share_b_b_l2
	    :derive-condition (at$agent$l2)
	    :parameters ()
	    :precondition (and
			(at_b_l2)
			(Bb_secret_b)
		)
	    :effect (and
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_Ba_not_secret_b)))
			(when (and (not (not_at_a_l2))) (not (PBa_not_secret_b)))
			(when (and (at_a_l2)) (not (Ba_not_secret_b)))
			(when (and (at_a_l2)) (PBa_secret_b))
			(when (and (at_a_l2)) (Ba_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBb_Ba_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Ba_PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (PBb_PBa_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Bb_PBa_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBa_Bb_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_Bb_not_secret_b)))
			(when (and (at_b_l2)) (not (PBb_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Ba_PBb_not_secret_b)))
			(when (and (not (not_at_a_l2))) (not (Ba_not_secret_b)))
			(when (and (not (not_at_b_l2))) (not (PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_PBb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (Bb_Ba_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBa_Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_Bb_not_secret_b)))
			(when (and (at_b_l2)) (Bb_secret_b))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (PBb_Ba_not_secret_b)))
			(when (and (at_b_l2)) (PBb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_PBa_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Bb_PBa_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (Ba_PBb_not_secret_b)))
			(when (and (at_a_l2)) (not (PBa_not_secret_b)))
			(when (and (not (not_at_a_l2)) (not (not_at_b_l2))) (not (Bb_Ba_not_secret_b)))
			(when (and (at_b_l2)) (not (Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (not (PBb_Ba_not_secret_b)))
			(when (and (not (not_at_b_l2))) (not (Bb_not_secret_b)))
			(when (and (at_a_l2) (at_b_l2)) (PBa_Bb_secret_b))
			(when (and (at_a_l2) (at_b_l2)) (Ba_Bb_secret_b))
		)
	)
)