QMRK: "?"
LSQB: "["
RSQB: "]"
BELIEF: "bel"
DESIRE: "des"
INTENTION: "itn"
DISDAIN: "dsd"
LOVE: "lov"
COMMA: ","
EXC: "!"
ANCEFFS_NAME: ":ancillary_effects"
ANCEFF_NAME: ":anceff"
ANT: ":antecedent"
CONS: ":consequent"
POSCOND: ":poscond"
NEGCOND: ":negcond"
RML_TYPE: ":rml"
COND_TYPE: ":type"
AWARENESS: ":need_awareness"
LCRL: "{"
RCRL: "}"
FOR: "for"
IN: "in"
RML_NAME: "rml"
PRED_NAME: "pred"
NESTING_NAME: "nesting"
ADD: "add"
DEL: "del"
ADD_SOFT: "add-soft"
DEL_SOFT: "del-soft"
WILDCARD: "wildcard"
DEL_WILDCARD: "del-wildcard"
TRUE_: "true"
FALSE_: "false"
AG: "?ag"
AGENTS: "?agents"
POS: "?pos"
NEG: "?neg"

start: domain [all_anceffs] [problem]

cond_types: ADD | DEL | ADD_SOFT | DEL_SOFT | WILDCARD | DEL_WILDCARD

var: QMRK NAME

modl_term: BELIEF | DESIRE | INTENTION | DISDAIN | LOVE

modl: [EXC] LSQB modl_term COMMA const_or_var_term RSQB | [EXC] LESSER_OP modl_term COMMA const_or_var_term GREATER_OP

modls_trailing_nesting: modl nesting_term

modls_leading_nesting: nesting_term modl

modls_leading_trailing_nesting: nesting_term modl nesting_term

modls: modl*

all_modl_nesting_options: modls_trailing_nesting | modls_leading_nesting | modls_leading_trailing_nesting

rml_options: list_comp_rml_var | list_comp_rml_agents | atomic_formula_term_anceff

rml_term_no_neg: LCRL RML_NAME RCRL

pred_term_no_neg: LCRL PRED_NAME RCRL 

rml_term: [EXC] LCRL RML_NAME RCRL

pred_term: [EXC] LCRL PRED_NAME RCRL 

nesting_term: LCRL NESTING_NAME RCRL

terminal_rml_or_pred: rml_term | pred_term

terminal_rml_or_pred_no_neg: rml_term_no_neg | pred_term_no_neg

pos_or_neg_term: POS | NEG

atomic_formula_term_rml: modls terminal_rml_or_pred

atomic_formula_term_nesting_term: all_modl_nesting_options terminal_rml_or_pred_no_neg

atomic_formula_term_anceff: atomic_formula_term_rml | atomic_formula_term_nesting_term

anceff_params: PARAMETERS action_parameters

ant_poscond: POSCOND POS

ant_negcond: NEGCOND NEG

cons_poscond: POSCOND pos_or_neg_cond

cons_negcond: NEGCOND pos_or_neg_cond

list_comp_rml_var: LCRL atomic_formula_term_rml FOR rml_term IN pos_or_neg_term RCRL

list_comp_rml_agents: LCRL atomic_formula_term_rml FOR AG IN AGENTS RCRL

pos_or_neg_cond_options: var | list_comp_rml_var | list_comp_rml_agents | atomic_formula_term_rml | gd

pos_or_neg_cond: pos_or_neg_cond_options (PLUS pos_or_neg_cond_options)*

rml_cons_def: RML_TYPE rml_options (PLUS rml_options)*

rml_ant_def: RML_TYPE atomic_formula_term_anceff

cond_type_def: COND_TYPE cond_types

antecedent: ANT LPAR ant_poscond ant_negcond [awareness] rml_ant_def cond_type_def RPAR

consequent: CONS LPAR [cons_poscond] [cons_negcond] rml_cons_def cond_type_def RPAR

awareness: AWARENESS TRUE_ | AWARENESS FALSE_

anceff: LPAR ANCEFF_NAME NAME [anceff_params] antecedent consequent RPAR

anceffs: LPAR ANCEFFS_NAME anceff* RPAR

all_anceffs: anceffs*