QMRK: "?"
LSQB: "["
RSQB: "]"
BELIEF: "bel"
DESIRE: "des"
INTENTION: "itn"
DISDAIN: "dsd"
LOVE: "lov"
COMMA: ","
EXC: "!"
ANCEFFS_NAME: ":ancillary_effects"
ANCEFF_NAME: ":anceff"
ANT: ":antecedent"
CONS: ":consequent"
POSCOND: ":poscond"
NEGCOND: ":negcond"
RML_TYPE: ":rml"
COND_TYPE: ":type"
AWARENESS: ":need_awareness"
LCRL: "{"
RCRL: "}"
FOR: "for"
IN: "in"
// R: "r"
RML_NAME: "rml"
PRED_NAME: "pred"
ADD: "add"
DEL: "del"
ADD_SOFT: "add-soft"
DEL_SOFT: "del-soft"
WILDCARD: "wildcard"
DEL_WILDCARD: "del-wildcard"
TRUE_: "true"
FALSE_: "false"
AG: "?ag"
AGENTS: "agents"
POS: "?pos"
NEG: "?neg"

start: domain [all_anceffs] [problem]

cond_types: ADD | DEL | ADD_SOFT | DEL_SOFT | WILDCARD | DEL_WILDCARD

var: QMRK NAME

modl_term: BELIEF | DESIRE | INTENTION | DISDAIN | LOVE

modl: [EXC] LSQB modl_term COMMA const_or_var_term RSQB | [EXC] LESSER_OP modl_term COMMA const_or_var_term GREATER_OP

rml_options: list_comp_r_var | list_comp_r_agents | list_comp_rml_var | list_comp_rml_agents | atomic_formula_term_rml | effect

rml_or_pred_term: RML_NAME | PRED_NAME

rml_term: [EXC] LCRL RML_NAME RCRL

pred_term: [EXC] LCRL PRED_NAME RCRL 

terminal_rml_nested: [EXC] LSQB rml_term RSQB

terminal_pred_nested: [EXC] LSQB pred_term RSQB

terminal_rml_or_pred: rml_term | pred_term | terminal_rml_nested | terminal_pred_nested

pos_or_neg_term: POS | NEG

atomic_formula_term_rml: modl* terminal_rml_or_pred

anceff_params: PARAMETERS action_parameters

ant_poscond: POSCOND POS

ant_negcond: NEGCOND NEG

cons_poscond: POSCOND pos_or_neg_cond

cons_negcond: NEGCOND pos_or_neg_cond

list_comp_r_var: LCRL atomic_formula_term_rml FOR rml_term IN pos_or_neg_term RCRL

list_comp_r_agents: LCRL atomic_formula_term_rml FOR AG IN AGENTS RCRL

list_comp_rml_var: LCRL atomic_formula_term_rml FOR rml_term IN pos_or_neg_term RCRL

list_comp_rml_agents: LCRL atomic_formula_term_rml FOR AG IN AGENTS RCRL

pos_or_neg_cond_options: var | list_comp_r_var | atomic_formula_term_rml | gd

pos_or_neg_cond: pos_or_neg_cond_options (PLUS pos_or_neg_cond_options)*

rml_def: RML_TYPE rml_options (PLUS rml_options)*

cond_type_def: COND_TYPE cond_types

antecedent: ANT LPAR ant_poscond ant_negcond [awareness] rml_def cond_type_def RPAR

consequent: CONS LPAR [cons_poscond] [cons_negcond] rml_def cond_type_def RPAR

awareness: AWARENESS TRUE_ | AWARENESS FALSE_

anceff: LPAR ANCEFF_NAME NAME [anceff_params] antecedent consequent RPAR

anceffs: LPAR ANCEFFS_NAME anceff* RPAR

all_anceffs: anceffs*