(define (domain proselytize)
	(:requirements :typing)
	(:types
	    agent loc
	)
	(:predicates
		(skeptical_cindy_bob)
		(not_connected_l1_l1)
		(Bbob_PBcindy_not_book-teachings)
		(Dbob_PBcindy_not_book-teachings)
		(Ibob_PBcindy_not_book-teachings)
		(Bbob_PDcindy_not_book-teachings)
		(Dbob_PDcindy_not_book-teachings)
		(Ibob_PDcindy_not_book-teachings)
		(Bbob_PIcindy_not_book-teachings)
		(Dbob_PIcindy_not_book-teachings)
		(Ibob_PIcindy_not_book-teachings)
		(Ibob_Ialice_book-teachings)
		(not_skeptical_bob_cindy)
		(skeptical_bob_bob)
		(not_at_bob_l1)
		(connected_l2_l2)
		(PBbob_PBbob_book-teachings)
		(PDbob_PBbob_book-teachings)
		(Bcindy_PBalice_book-teachings)
		(Dcindy_PBalice_book-teachings)
		(Bcindy_Bcindy_book-teachings)
		(Dcindy_Bcindy_book-teachings)
		(Icindy_Bcindy_book-teachings)
		(Bcindy_Dcindy_book-teachings)
		(Dcindy_Dcindy_book-teachings)
		(Icindy_Dcindy_book-teachings)
		(Bcindy_Icindy_book-teachings)
		(Dcindy_Icindy_book-teachings)
		(Icindy_Icindy_book-teachings)
		(leader_alice)
		(PBbob_PBcindy_book-teachings)
		(Balice_Ibob_book-teachings)
		(Dalice_Ibob_book-teachings)
		(Ialice_Ibob_book-teachings)
		(PDbob_PBcindy_book-teachings)
		(PIbob_PBcindy_book-teachings)
		(PBbob_PDcindy_book-teachings)
		(PDbob_PDcindy_book-teachings)
		(PIbob_PDcindy_book-teachings)
		(PBbob_PIcindy_book-teachings)
		(PBbob_Balice_not_book-teachings)
		(PDbob_Balice_not_book-teachings)
		(PIbob_Balice_not_book-teachings)
		(PBbob_Dalice_not_book-teachings)
		(PDbob_Dalice_not_book-teachings)
		(Bcindy_PBcindy_not_book-teachings)
		(Dcindy_PBcindy_not_book-teachings)
		(Icindy_PBcindy_not_book-teachings)
		(Bcindy_PDcindy_not_book-teachings)
		(Dcindy_PDcindy_not_book-teachings)
		(Icindy_PDcindy_not_book-teachings)
		(Bbob_not_book-teachings)
		(Dbob_not_book-teachings)
		(Ibob_not_book-teachings)
		(Bcindy_PIcindy_not_book-teachings)
		(book-at_l1)
		(Bbob_PBcindy_book-teachings)
		(Dbob_PBcindy_book-teachings)
		(Ibob_PBcindy_book-teachings)
		(Bbob_PDcindy_book-teachings)
		(Dbob_PDcindy_book-teachings)
		(Ibob_PDcindy_book-teachings)
		(Bbob_PIcindy_book-teachings)
		(Dbob_PIcindy_book-teachings)
		(Ibob_PIcindy_book-teachings)
		(not_skeptical_cindy_bob)
		(PBalice_Bbob_not_book-teachings)
		(PDalice_Bbob_not_book-teachings)
		(PIalice_Bbob_not_book-teachings)
		(PBalice_Dbob_not_book-teachings)
		(PDalice_Dbob_not_book-teachings)
		(PIalice_Dbob_not_book-teachings)
		(PBalice_Ibob_not_book-teachings)
		(PDalice_Ibob_not_book-teachings)
		(PIalice_Ibob_not_book-teachings)
		(connected_l1_l2)
		(Balice_PBbob_not_book-teachings)
		(Dalice_PBbob_not_book-teachings)
		(Ialice_PBbob_not_book-teachings)
		(Balice_PDbob_not_book-teachings)
		(Dalice_PDbob_not_book-teachings)
		(Ialice_PDbob_not_book-teachings)
		(Balice_PIbob_not_book-teachings)
		(Dalice_PIbob_not_book-teachings)
		(Ialice_PIbob_not_book-teachings)
		(PIbob_PIbob_not_book-teachings)
		(PBbob_PBalice_book-teachings)
		(PDbob_PBalice_book-teachings)
		(Icindy_Icindy_not_book-teachings)
		(Bcindy_Bcindy_not_book-teachings)
		(Dcindy_Bcindy_not_book-teachings)
		(Icindy_Bcindy_not_book-teachings)
		(Bcindy_Dcindy_not_book-teachings)
		(Dcindy_Dcindy_not_book-teachings)
		(Icindy_Dcindy_not_book-teachings)
		(Bcindy_Icindy_not_book-teachings)
		(Dcindy_Icindy_not_book-teachings)
		(Ibob_PBalice_book-teachings)
		(Bbob_PDalice_book-teachings)
		(PBbob_Bbob_book-teachings)
		(PDbob_Bbob_book-teachings)
		(PIbob_Bbob_book-teachings)
		(PBbob_Dbob_book-teachings)
		(PDbob_Dbob_book-teachings)
		(PIbob_Dbob_book-teachings)
		(PBbob_Ibob_book-teachings)
		(PIalice_PDcindy_not_book-teachings)
		(PBalice_PIcindy_not_book-teachings)
		(PDalice_PIcindy_not_book-teachings)
		(PIalice_PIcindy_not_book-teachings)
		(PIbob_PBalice_book-teachings)
		(PBbob_PDalice_book-teachings)
		(PDbob_PDalice_book-teachings)
		(PIbob_PDalice_book-teachings)
		(not_connected_l1_l2)
		(PBbob_PIalice_book-teachings)
		(PDbob_PIalice_book-teachings)
		(PIbob_PIalice_book-teachings)
		(PBcindy_PBbob_not_book-teachings)
		(PDcindy_PBbob_not_book-teachings)
		(PIcindy_PBbob_not_book-teachings)
		(PBcindy_PDbob_not_book-teachings)
		(PDcindy_PDbob_not_book-teachings)
		(PIcindy_PDbob_not_book-teachings)
		(PBcindy_PIbob_not_book-teachings)
		(PBcindy_book-teachings)
		(PDcindy_book-teachings)
		(PIcindy_book-teachings)
		(PBbob_Balice_book-teachings)
		(PDbob_Balice_book-teachings)
		(PIbob_Balice_book-teachings)
		(PBbob_Dalice_book-teachings)
		(PDbob_Dalice_book-teachings)
		(PIbob_Dalice_book-teachings)
		(Icindy_Bbob_not_book-teachings)
		(Bcindy_Dbob_not_book-teachings)
		(Dcindy_Dbob_not_book-teachings)
		(Icindy_Dbob_not_book-teachings)
		(Bcindy_Ibob_not_book-teachings)
		(Dcindy_Ibob_not_book-teachings)
		(Icindy_Ibob_not_book-teachings)
		(Bcindy_Bbob_not_book-teachings)
		(not_leader_cindy)
		(not_at_bob_l2)
		(connected_l2_l1)
		(not_follower_bob_alice)
		(Bbob_Balice_book-teachings)
		(Dbob_Balice_book-teachings)
		(Ibob_Balice_book-teachings)
		(Bbob_Dalice_book-teachings)
		(Dbob_Dalice_book-teachings)
		(Ibob_Dalice_book-teachings)
		(Bbob_Ialice_book-teachings)
		(Dbob_Ialice_book-teachings)
		(Bcindy_not_book-teachings)
		(Dcindy_not_book-teachings)
		(Icindy_not_book-teachings)
		(PDalice_Bbob_book-teachings)
		(PIalice_Bbob_book-teachings)
		(PBalice_Dbob_book-teachings)
		(PDalice_Dbob_book-teachings)
		(PIalice_Dbob_book-teachings)
		(PBalice_Ibob_book-teachings)
		(PDalice_Ibob_book-teachings)
		(PIalice_Ibob_book-teachings)
		(PBcindy_PBalice_book-teachings)
		(PDcindy_PBalice_book-teachings)
		(PIcindy_PBalice_book-teachings)
		(PBcindy_PDalice_book-teachings)
		(PDcindy_PDalice_book-teachings)
		(PIcindy_PDalice_book-teachings)
		(PBcindy_PIalice_book-teachings)
		(PDcindy_PIalice_book-teachings)
		(PIcindy_PIalice_book-teachings)
		(PDcindy_Dbob_book-teachings)
		(PIcindy_Dbob_book-teachings)
		(PBcindy_Ibob_book-teachings)
		(PDcindy_Ibob_book-teachings)
		(PIcindy_Ibob_book-teachings)
		(PBcindy_Bbob_book-teachings)
		(PDcindy_Bbob_book-teachings)
		(PIcindy_Bbob_book-teachings)
		(PBcindy_Dbob_book-teachings)
		(PDcindy_PDbob_book-teachings)
		(PIcindy_PDbob_book-teachings)
		(PBcindy_PIbob_book-teachings)
		(PDcindy_PIbob_book-teachings)
		(PIcindy_PIbob_book-teachings)
		(PDcindy_PBbob_book-teachings)
		(PIcindy_PBbob_book-teachings)
		(PBcindy_PDbob_book-teachings)
		(PBcindy_PBbob_book-teachings)
		(PDbob_Ibob_book-teachings)
		(PIalice_PIbob_book-teachings)
		(PIbob_Ibob_book-teachings)
		(Dcindy_PIalice_not_book-teachings)
		(Icindy_PIalice_not_book-teachings)
		(skeptical_alice_cindy)
		(Balice_Balice_not_book-teachings)
		(Dalice_Balice_not_book-teachings)
		(Ialice_Balice_not_book-teachings)
		(Balice_Dalice_not_book-teachings)
		(Dalice_Dalice_not_book-teachings)
		(Ialice_Dalice_not_book-teachings)
		(Balice_Ialice_not_book-teachings)
		(not_book-at_l2)
		(Dalice_Ialice_not_book-teachings)
		(Ialice_Ialice_not_book-teachings)
		(PBalice_PBbob_not_book-teachings)
		(PDalice_PBbob_not_book-teachings)
		(PIalice_PBbob_not_book-teachings)
		(PBalice_PDbob_not_book-teachings)
		(PDalice_PDbob_not_book-teachings)
		(PIalice_PDbob_not_book-teachings)
		(PBalice_PIbob_not_book-teachings)
		(PDalice_PIbob_not_book-teachings)
		(PIalice_PIbob_not_book-teachings)
		(skeptical_alice_bob)
		(PBbob_Bbob_not_book-teachings)
		(PDbob_Bbob_not_book-teachings)
		(PIbob_Bbob_not_book-teachings)
		(PBbob_Dbob_not_book-teachings)
		(PDbob_Dbob_not_book-teachings)
		(PIbob_Dbob_not_book-teachings)
		(PBbob_Ibob_not_book-teachings)
		(PDbob_Ibob_not_book-teachings)
		(PIbob_Ibob_not_book-teachings)
		(follower_bob_cindy)
		(not_follower_cindy_bob)
		(skeptical_alice_alice)
		(not_at_alice_l1)
		(skeptical_bob_alice)
		(PBcindy_PBcindy_not_book-teachings)
		(PDcindy_PBcindy_not_book-teachings)
		(PIcindy_PBcindy_not_book-teachings)
		(PBcindy_PDcindy_not_book-teachings)
		(PDcindy_PDcindy_not_book-teachings)
		(PIcindy_PDcindy_not_book-teachings)
		(PBcindy_PIcindy_not_book-teachings)
		(PDcindy_PIcindy_not_book-teachings)
		(PIcindy_PIcindy_not_book-teachings)
		(PBbob_PIbob_not_book-teachings)
		(PDbob_PIbob_not_book-teachings)
		(Dbob_PDalice_book-teachings)
		(Ibob_PDalice_book-teachings)
		(Bbob_PIalice_book-teachings)
		(Dbob_PIalice_book-teachings)
		(Ibob_PIalice_book-teachings)
		(PBbob_Ialice_book-teachings)
		(PDbob_Ialice_book-teachings)
		(PIbob_Ialice_book-teachings)
		(Bcindy_PBbob_not_book-teachings)
		(Dcindy_PBbob_not_book-teachings)
		(Icindy_PBbob_not_book-teachings)
		(Bcindy_PDbob_not_book-teachings)
		(Dcindy_PDbob_not_book-teachings)
		(Icindy_PDbob_not_book-teachings)
		(Bcindy_PIbob_not_book-teachings)
		(Dcindy_PIbob_not_book-teachings)
		(Icindy_PIbob_not_book-teachings)
		(PBcindy_PBcindy_book-teachings)
		(PDcindy_PBcindy_book-teachings)
		(PIcindy_PBcindy_book-teachings)
		(PBcindy_PDcindy_book-teachings)
		(PDcindy_PDcindy_book-teachings)
		(PIcindy_PDcindy_book-teachings)
		(PBcindy_PIcindy_book-teachings)
		(PDcindy_PIcindy_book-teachings)
		(PIcindy_PIcindy_book-teachings)
		(Bbob_Bbob_not_book-teachings)
		(Dbob_Bbob_not_book-teachings)
		(Ibob_Bbob_not_book-teachings)
		(Bbob_Dbob_not_book-teachings)
		(PBalice_PBalice_not_book-teachings)
		(PDalice_PBalice_not_book-teachings)
		(PIalice_PBalice_not_book-teachings)
		(PBalice_PDalice_not_book-teachings)
		(PDalice_PDalice_not_book-teachings)
		(PIalice_PDalice_not_book-teachings)
		(PBalice_PIalice_not_book-teachings)
		(PDalice_PIalice_not_book-teachings)
		(PIalice_PIalice_not_book-teachings)
		(not_connected_l2_l2)
		(not_book-teachings)
		(skeptical_cindy_alice)
		(not_leader_alice)
		(skeptical_cindy_cindy)
		(PBcindy_Bcindy_not_book-teachings)
		(PDcindy_Bcindy_not_book-teachings)
		(PIcindy_Bcindy_not_book-teachings)
		(PBcindy_Dcindy_not_book-teachings)
		(PDcindy_Dcindy_not_book-teachings)
		(PIcindy_Dcindy_not_book-teachings)
		(PBcindy_Icindy_not_book-teachings)
		(PDcindy_Icindy_not_book-teachings)
		(PIcindy_Icindy_not_book-teachings)
		(follower_alice_alice)
		(Balice_PBalice_not_book-teachings)
		(Dalice_PBalice_not_book-teachings)
		(Ialice_PBalice_not_book-teachings)
		(Balice_PDalice_not_book-teachings)
		(Dalice_PDalice_not_book-teachings)
		(Ialice_PDalice_not_book-teachings)
		(Balice_PIalice_not_book-teachings)
		(Dalice_PIalice_not_book-teachings)
		(Ialice_PIalice_not_book-teachings)
		(at_alice_l2)
		(Bbob_Balice_not_book-teachings)
		(Dbob_Balice_not_book-teachings)
		(Ibob_Balice_not_book-teachings)
		(Bbob_Dalice_not_book-teachings)
		(Dbob_Dalice_not_book-teachings)
		(Ibob_Dalice_not_book-teachings)
		(Bbob_Ialice_not_book-teachings)
		(Dbob_Ialice_not_book-teachings)
		(Ibob_Ialice_not_book-teachings)
		(PBalice_PBcindy_not_book-teachings)
		(PDalice_PBcindy_not_book-teachings)
		(PIalice_PBcindy_not_book-teachings)
		(PBalice_PDcindy_not_book-teachings)
		(PDalice_PDcindy_not_book-teachings)
		(PBcindy_Bcindy_book-teachings)
		(PDcindy_Bcindy_book-teachings)
		(PIcindy_Bcindy_book-teachings)
		(PBcindy_Dcindy_book-teachings)
		(PDcindy_Dcindy_book-teachings)
		(PIcindy_Dcindy_book-teachings)
		(PBcindy_Icindy_book-teachings)
		(PDcindy_Icindy_book-teachings)
		(PIcindy_Icindy_book-teachings)
		(Dbob_PBbob_book-teachings)
		(Ibob_PBbob_book-teachings)
		(not_skeptical_bob_bob)
		(not_skeptical_cindy_alice)
		(not_book-at_l1)
		(not_follower_alice_alice)
		(connected_l1_l1)
		(PIbob_Bcindy_book-teachings)
		(PBbob_Dcindy_book-teachings)
		(PDbob_Dcindy_book-teachings)
		(PIbob_Dcindy_book-teachings)
		(PBbob_Icindy_book-teachings)
		(PDbob_Icindy_book-teachings)
		(PIbob_Icindy_book-teachings)
		(follower_alice_cindy)
		(PBbob_PBbob_not_book-teachings)
		(PDbob_PBbob_not_book-teachings)
		(PIbob_PBbob_not_book-teachings)
		(PBbob_PDbob_not_book-teachings)
		(PDbob_PDbob_not_book-teachings)
		(PIbob_PDbob_not_book-teachings)
		(PDalice_Bcindy_not_book-teachings)
		(PBalice_Bcindy_not_book-teachings)
		(PIalice_Bcindy_not_book-teachings)
		(PBalice_Dcindy_not_book-teachings)
		(PDalice_Dcindy_not_book-teachings)
		(PIalice_Dcindy_not_book-teachings)
		(PBalice_Icindy_not_book-teachings)
		(PDalice_Icindy_not_book-teachings)
		(PIalice_Icindy_not_book-teachings)
		(PIbob_PIcindy_not_book-teachings)
		(Balice_Bcindy_not_book-teachings)
		(Dalice_Bcindy_not_book-teachings)
		(Ialice_Bcindy_not_book-teachings)
		(Balice_Dcindy_not_book-teachings)
		(Dalice_Dcindy_not_book-teachings)
		(Ialice_Dcindy_not_book-teachings)
		(Balice_Icindy_not_book-teachings)
		(Dalice_Icindy_not_book-teachings)
		(Ialice_Icindy_not_book-teachings)
		(PBcindy_Balice_book-teachings)
		(PDcindy_Balice_book-teachings)
		(PIcindy_Balice_book-teachings)
		(PBcindy_Dalice_book-teachings)
		(PDcindy_Dalice_book-teachings)
		(PIcindy_Dalice_book-teachings)
		(PBcindy_Ialice_book-teachings)
		(PDcindy_Ialice_book-teachings)
		(PIcindy_Ialice_book-teachings)
		(PBcindy_Dbob_not_book-teachings)
		(PDcindy_Dbob_not_book-teachings)
		(Dcindy_Bbob_not_book-teachings)
		(Bbob_PBbob_not_book-teachings)
		(Dbob_PBbob_not_book-teachings)
		(Ibob_PBbob_not_book-teachings)
		(Bbob_PDbob_not_book-teachings)
		(Dbob_PDbob_not_book-teachings)
		(Ibob_PDbob_not_book-teachings)
		(Bbob_PIbob_not_book-teachings)
		(Dbob_PIbob_not_book-teachings)
		(Ibob_PIbob_not_book-teachings)
		(not_follower_alice_cindy)
		(PBbob_PBalice_not_book-teachings)
		(PDbob_PBalice_not_book-teachings)
		(PIbob_PBalice_not_book-teachings)
		(PBbob_PDalice_not_book-teachings)
		(PDbob_PDalice_not_book-teachings)
		(PIbob_PDalice_not_book-teachings)
		(PBbob_PIalice_not_book-teachings)
		(PDbob_PIalice_not_book-teachings)
		(PIbob_PIalice_not_book-teachings)
		(follower_cindy_cindy)
		(PDbob_PIcindy_book-teachings)
		(PIbob_PIcindy_book-teachings)
		(not_connected_l2_l1)
		(PBalice_Bcindy_book-teachings)
		(PDalice_Bcindy_book-teachings)
		(PIalice_Bcindy_book-teachings)
		(PBalice_Dcindy_book-teachings)
		(PDalice_Dcindy_book-teachings)
		(PIalice_Dcindy_book-teachings)
		(PBalice_Icindy_book-teachings)
		(PDalice_Icindy_book-teachings)
		(PIalice_Icindy_book-teachings)
		(PBbob_PBcindy_not_book-teachings)
		(PDbob_PBcindy_not_book-teachings)
		(PIbob_PBcindy_not_book-teachings)
		(PBbob_PDcindy_not_book-teachings)
		(PDbob_PDcindy_not_book-teachings)
		(PIbob_PDcindy_not_book-teachings)
		(PBbob_PIcindy_not_book-teachings)
		(Dalice_Ibob_not_book-teachings)
		(Ialice_Ibob_not_book-teachings)
		(PDbob_PIcindy_not_book-teachings)
		(follower_bob_bob)
		(Bcindy_Balice_not_book-teachings)
		(Dcindy_Balice_not_book-teachings)
		(Icindy_Balice_not_book-teachings)
		(Bcindy_Dalice_not_book-teachings)
		(Dcindy_Dalice_not_book-teachings)
		(Icindy_Dalice_not_book-teachings)
		(Bcindy_Ialice_not_book-teachings)
		(Dcindy_Ialice_not_book-teachings)
		(not_skeptical_alice_cindy)
		(Icindy_Ialice_not_book-teachings)
		(follower_cindy_alice)
		(Balice_book-teachings)
		(Dalice_book-teachings)
		(Ialice_book-teachings)
		(Bbob_PBalice_not_book-teachings)
		(Dbob_PBalice_not_book-teachings)
		(Ibob_PBalice_not_book-teachings)
		(Bbob_PDalice_not_book-teachings)
		(not_follower_cindy_alice)
		(PBalice_Bbob_book-teachings)
		(Bcindy_Ialice_book-teachings)
		(Dcindy_Ialice_book-teachings)
		(Icindy_Ialice_book-teachings)
		(Bcindy_Balice_book-teachings)
		(not_skeptical_alice_bob)
		(Dcindy_Balice_book-teachings)
		(PBcindy_not_book-teachings)
		(PDcindy_not_book-teachings)
		(PIcindy_not_book-teachings)
		(Icindy_Balice_book-teachings)
		(PBalice_PBbob_book-teachings)
		(PDalice_PBbob_book-teachings)
		(PIalice_PBbob_book-teachings)
		(PBalice_PDbob_book-teachings)
		(PDalice_PDbob_book-teachings)
		(PIalice_PDbob_book-teachings)
		(PBalice_PIbob_book-teachings)
		(PDalice_PIbob_book-teachings)
		(not_follower_bob_cindy)
		(skeptical_bob_cindy)
		(Balice_PBcindy_book-teachings)
		(Dalice_PBcindy_book-teachings)
		(Ialice_PBcindy_book-teachings)
		(Balice_PDcindy_book-teachings)
		(Dalice_PDcindy_book-teachings)
		(Ialice_PDcindy_book-teachings)
		(Balice_PIcindy_book-teachings)
		(Dalice_PIcindy_book-teachings)
		(Ialice_PIcindy_book-teachings)
		(Bbob_Bcindy_not_book-teachings)
		(Dbob_Bcindy_not_book-teachings)
		(Ibob_Bcindy_not_book-teachings)
		(Bbob_Dcindy_not_book-teachings)
		(Dbob_Dcindy_not_book-teachings)
		(Ibob_Dcindy_not_book-teachings)
		(Bbob_Icindy_not_book-teachings)
		(Dbob_Icindy_not_book-teachings)
		(Ibob_Icindy_not_book-teachings)
		(at_bob_l1)
		(Bbob_PDbob_book-teachings)
		(Dbob_PDbob_book-teachings)
		(Ibob_PDbob_book-teachings)
		(Bbob_PIbob_book-teachings)
		(Dbob_PIbob_book-teachings)
		(not_skeptical_bob_alice)
		(Ibob_PIbob_book-teachings)
		(PBalice_PBalice_book-teachings)
		(PDalice_PBalice_book-teachings)
		(PIalice_PBalice_book-teachings)
		(PBalice_PDalice_book-teachings)
		(PDalice_PDalice_book-teachings)
		(PIalice_PDalice_book-teachings)
		(PBalice_PIalice_book-teachings)
		(PDalice_PIalice_book-teachings)
		(PIalice_PIalice_book-teachings)
		(Balice_Bcindy_book-teachings)
		(Dalice_Bcindy_book-teachings)
		(Ialice_Bcindy_book-teachings)
		(Balice_Dcindy_book-teachings)
		(Dalice_Dcindy_book-teachings)
		(Ialice_Dcindy_book-teachings)
		(Balice_Icindy_book-teachings)
		(Dalice_Icindy_book-teachings)
		(Ialice_Icindy_book-teachings)
		(follower_bob_alice)
		(Bcindy_PBalice_not_book-teachings)
		(Dcindy_PBalice_not_book-teachings)
		(Icindy_PBalice_not_book-teachings)
		(Bcindy_PDalice_not_book-teachings)
		(Dcindy_PDalice_not_book-teachings)
		(PBbob_book-teachings)
		(PDbob_book-teachings)
		(PIbob_book-teachings)
		(Icindy_PDalice_not_book-teachings)
		(Bcindy_PIalice_not_book-teachings)
		(Dbob_Dbob_not_book-teachings)
		(Ibob_Dbob_not_book-teachings)
		(Bbob_Ibob_not_book-teachings)
		(Dbob_Ibob_not_book-teachings)
		(Ibob_Ibob_not_book-teachings)
		(Balice_PBalice_book-teachings)
		(Dalice_PBalice_book-teachings)
		(Ialice_PBalice_book-teachings)
		(Balice_PDalice_book-teachings)
		(Dalice_PDalice_book-teachings)
		(Ialice_PDalice_book-teachings)
		(Balice_PIalice_book-teachings)
		(Dalice_PIalice_book-teachings)
		(Ialice_PIalice_book-teachings)
		(PBbob_Bcindy_book-teachings)
		(PDbob_Bcindy_book-teachings)
		(PIcindy_Dbob_not_book-teachings)
		(PBcindy_Ibob_not_book-teachings)
		(PDcindy_Ibob_not_book-teachings)
		(PIcindy_Ibob_not_book-teachings)
		(PBalice_not_book-teachings)
		(PDalice_not_book-teachings)
		(PIalice_not_book-teachings)
		(PBcindy_Bbob_not_book-teachings)
		(PDcindy_Bbob_not_book-teachings)
		(PIcindy_Bbob_not_book-teachings)
		(Balice_Bbob_book-teachings)
		(Dalice_Bbob_book-teachings)
		(Ialice_Bbob_book-teachings)
		(Balice_Dbob_book-teachings)
		(Dalice_Dbob_book-teachings)
		(Ialice_Dbob_book-teachings)
		(Balice_PBbob_book-teachings)
		(Dalice_PBbob_book-teachings)
		(Ialice_PBbob_book-teachings)
		(Balice_PDbob_book-teachings)
		(Dalice_PDbob_book-teachings)
		(Ialice_PDbob_book-teachings)
		(Balice_PIbob_book-teachings)
		(Dalice_PIbob_book-teachings)
		(Ialice_PIbob_book-teachings)
		(at_cindy_l1)
		(not_skeptical_cindy_cindy)
		(Balice_Balice_book-teachings)
		(Dalice_Balice_book-teachings)
		(Ialice_Balice_book-teachings)
		(Balice_Dalice_book-teachings)
		(Dalice_Dalice_book-teachings)
		(Ialice_Dalice_book-teachings)
		(Balice_Ialice_book-teachings)
		(Dalice_Ialice_book-teachings)
		(Ialice_Ialice_book-teachings)
		(not_at_alice_l2)
		(PBcindy_Balice_not_book-teachings)
		(PDcindy_Balice_not_book-teachings)
		(PIcindy_Balice_not_book-teachings)
		(PBcindy_Dalice_not_book-teachings)
		(PDcindy_Dalice_not_book-teachings)
		(PIcindy_Dalice_not_book-teachings)
		(PBcindy_Ialice_not_book-teachings)
		(PDcindy_Ialice_not_book-teachings)
		(PIcindy_Ialice_not_book-teachings)
		(leader_bob)
		(PBalice_Ialice_not_book-teachings)
		(PDalice_Ialice_not_book-teachings)
		(PIalice_Ialice_not_book-teachings)
		(PIbob_PBbob_book-teachings)
		(PBbob_PDbob_book-teachings)
		(PDbob_PDbob_book-teachings)
		(PIbob_PDbob_book-teachings)
		(PBbob_PIbob_book-teachings)
		(PDbob_PIbob_book-teachings)
		(PIbob_PIbob_book-teachings)
		(not_at_cindy_l1)
		(PIbob_Icindy_not_book-teachings)
		(PDalice_Ialice_book-teachings)
		(PIalice_Ialice_book-teachings)
		(follower_alice_bob)
		(leader_cindy)
		(at_bob_l2)
		(not_leader_bob)
		(book-at_l2)
		(at_cindy_l2)
		(Bbob_book-teachings)
		(Dbob_book-teachings)
		(Ibob_book-teachings)
		(Balice_PBcindy_not_book-teachings)
		(Dalice_PBcindy_not_book-teachings)
		(Ialice_PBcindy_not_book-teachings)
		(Balice_PDcindy_not_book-teachings)
		(Dalice_PDcindy_not_book-teachings)
		(Ialice_PDcindy_not_book-teachings)
		(Balice_PIcindy_not_book-teachings)
		(Dalice_PIcindy_not_book-teachings)
		(Ialice_PIcindy_not_book-teachings)
		(PBalice_Balice_not_book-teachings)
		(PDalice_Balice_not_book-teachings)
		(PIalice_Balice_not_book-teachings)
		(PBalice_Dalice_not_book-teachings)
		(PDalice_Dalice_not_book-teachings)
		(PIalice_Dalice_not_book-teachings)
		(Bbob_Bcindy_book-teachings)
		(Dbob_Bcindy_book-teachings)
		(Ibob_Bcindy_book-teachings)
		(Bbob_Dcindy_book-teachings)
		(Dbob_Dcindy_book-teachings)
		(Ibob_Dcindy_book-teachings)
		(Bbob_Icindy_book-teachings)
		(Dbob_Icindy_book-teachings)
		(Ibob_Icindy_book-teachings)
		(not_follower_alice_bob)
		(PIbob_Dalice_not_book-teachings)
		(PBbob_Ialice_not_book-teachings)
		(PDbob_Ialice_not_book-teachings)
		(PIbob_Ialice_not_book-teachings)
		(PBalice_book-teachings)
		(PDalice_book-teachings)
		(PIalice_book-teachings)
		(Bbob_PBalice_book-teachings)
		(Dbob_PBalice_book-teachings)
		(PBbob_Bcindy_not_book-teachings)
		(PDbob_Bcindy_not_book-teachings)
		(PIbob_Bcindy_not_book-teachings)
		(PBbob_Dcindy_not_book-teachings)
		(PDbob_Dcindy_not_book-teachings)
		(PIbob_Dcindy_not_book-teachings)
		(PBbob_Icindy_not_book-teachings)
		(not_skeptical_alice_alice)
		(PDbob_Icindy_not_book-teachings)
		(PBbob_not_book-teachings)
		(PDbob_not_book-teachings)
		(PIbob_not_book-teachings)
		(at_alice_l1)
		(Bbob_Bbob_book-teachings)
		(Dbob_Bbob_book-teachings)
		(Ibob_Bbob_book-teachings)
		(Bbob_Dbob_book-teachings)
		(Dbob_Dbob_book-teachings)
		(Ibob_Dbob_book-teachings)
		(Bbob_Ibob_book-teachings)
		(Dbob_Ibob_book-teachings)
		(Ibob_Ibob_book-teachings)
		(PBcindy_PIalice_not_book-teachings)
		(PDcindy_PIalice_not_book-teachings)
		(PIcindy_PIalice_not_book-teachings)
		(PBcindy_PBalice_not_book-teachings)
		(PDcindy_PBalice_not_book-teachings)
		(PIcindy_PBalice_not_book-teachings)
		(PBcindy_PDalice_not_book-teachings)
		(PDcindy_PDalice_not_book-teachings)
		(PIcindy_PDalice_not_book-teachings)
		(Bbob_PBbob_book-teachings)
		(not_follower_cindy_cindy)
		(PBalice_PBcindy_book-teachings)
		(PDalice_PBcindy_book-teachings)
		(PIalice_PBcindy_book-teachings)
		(PBalice_PDcindy_book-teachings)
		(PDalice_PDcindy_book-teachings)
		(PIalice_PDcindy_book-teachings)
		(PBalice_PIcindy_book-teachings)
		(PDalice_PIcindy_book-teachings)
		(PIalice_PIcindy_book-teachings)
		(Balice_Bbob_not_book-teachings)
		(Dalice_Bbob_not_book-teachings)
		(Ialice_Bbob_not_book-teachings)
		(Balice_Dbob_not_book-teachings)
		(Bcindy_book-teachings)
		(Dcindy_book-teachings)
		(Icindy_book-teachings)
		(Dalice_Dbob_not_book-teachings)
		(Ialice_Dbob_not_book-teachings)
		(Balice_Ibob_not_book-teachings)
		(Balice_not_book-teachings)
		(Dalice_not_book-teachings)
		(Ialice_not_book-teachings)
		(follower_cindy_bob)
		(PDcindy_PIbob_not_book-teachings)
		(PIcindy_PIbob_not_book-teachings)
		(not_at_cindy_l2)
		(not_follower_bob_bob)
		(PBalice_Balice_book-teachings)
		(PDalice_Balice_book-teachings)
		(PIalice_Balice_book-teachings)
		(PBalice_Dalice_book-teachings)
		(PDalice_Dalice_book-teachings)
		(PIalice_Dalice_book-teachings)
		(PBalice_Ialice_book-teachings)
		(Bcindy_PBcindy_book-teachings)
		(Dcindy_PBcindy_book-teachings)
		(Icindy_PBcindy_book-teachings)
		(Bcindy_PDcindy_book-teachings)
		(Dcindy_PDcindy_book-teachings)
		(Icindy_PDcindy_book-teachings)
		(Bcindy_PIcindy_book-teachings)
		(Dcindy_PIcindy_book-teachings)
		(Icindy_PIcindy_book-teachings)
		(Bcindy_Dalice_book-teachings)
		(Dcindy_Dalice_book-teachings)
		(Icindy_Dalice_book-teachings)
		(book-teachings)
		(Icindy_Ibob_book-teachings)
		(Icindy_Bbob_book-teachings)
		(Bcindy_Dbob_book-teachings)
		(Dcindy_Dbob_book-teachings)
		(Icindy_Dbob_book-teachings)
		(Bcindy_Ibob_book-teachings)
		(Dcindy_Ibob_book-teachings)
		(Bcindy_Bbob_book-teachings)
		(Dcindy_Bbob_book-teachings)
		(Bcindy_PIbob_book-teachings)
		(Dcindy_PIbob_book-teachings)
		(Icindy_PIbob_book-teachings)
		(Bcindy_PBbob_book-teachings)
		(Dcindy_PBbob_book-teachings)
		(Icindy_PBbob_book-teachings)
		(Bcindy_PDbob_book-teachings)
		(Dcindy_PDbob_book-teachings)
		(Icindy_PDbob_book-teachings)
		(Dcindy_PIcindy_not_book-teachings)
		(Icindy_PIcindy_not_book-teachings)
		(Icindy_PBalice_book-teachings)
		(Bcindy_PDalice_book-teachings)
		(Dcindy_PDalice_book-teachings)
		(Icindy_PDalice_book-teachings)
		(Bcindy_PIalice_book-teachings)
		(Dcindy_PIalice_book-teachings)
		(Icindy_PIalice_book-teachings)
		(Dbob_PDalice_not_book-teachings)
		(Ibob_PDalice_not_book-teachings)
		(Bbob_PIalice_not_book-teachings)
		(Dbob_PIalice_not_book-teachings)
		(Ibob_PIalice_not_book-teachings)
	)
	(:action adopt-belief_alice_l1
	    :parameters ()
	    :precondition (and
			(leader_alice)
			(at_alice_l1)
			(book-at_l1)
		)
	    :effect (and
			(PBalice_book-teachings)
			(not (PDalice_PBcindy_not_book-teachings))
			(Dalice_Bcindy_book-teachings)
			(Dalice_Bbob_book-teachings)
			(Balice_book-teachings)
			(not (PDalice_PBalice_not_book-teachings))
			(Dalice_Balice_book-teachings)
			(not (PBalice_not_book-teachings))
			(not (Balice_not_book-teachings))
			(not (PDalice_PBbob_not_book-teachings))
		)
	)
	 (:action adopt-belief_alice_l2
	    :parameters ()
	    :precondition (and
			(leader_alice)
			(at_alice_l2)
			(book-at_l2)
		)
	    :effect (and
			(PBalice_book-teachings)
			(not (PDalice_PBcindy_not_book-teachings))
			(Dalice_Bcindy_book-teachings)
			(Dalice_Bbob_book-teachings)
			(Balice_book-teachings)
			(not (PDalice_PBalice_not_book-teachings))
			(Dalice_Balice_book-teachings)
			(not (PBalice_not_book-teachings))
			(not (Balice_not_book-teachings))
			(not (PDalice_PBbob_not_book-teachings))
		)
	)
	 (:action adopt-belief_bob_l1
	    :parameters ()
	    :precondition (and
			(leader_bob)
			(at_bob_l1)
			(book-at_l1)
		)
	    :effect (and
			(Bbob_book-teachings)
			(not (PDbob_PBcindy_not_book-teachings))
			(Dbob_Balice_book-teachings)
			(Dbob_Bcindy_book-teachings)
			(Dbob_Bbob_book-teachings)
			(not (PDbob_PBbob_not_book-teachings))
			(not (PDbob_PBalice_not_book-teachings))
			(PBbob_book-teachings)
			(not (PBbob_not_book-teachings))
			(not (Bbob_not_book-teachings))
		)
	)
	 (:action adopt-belief_bob_l2
	    :parameters ()
	    :precondition (and
			(leader_bob)
			(at_bob_l2)
			(book-at_l2)
		)
	    :effect (and
			(Bbob_book-teachings)
			(not (PDbob_PBcindy_not_book-teachings))
			(Dbob_Balice_book-teachings)
			(Dbob_Bcindy_book-teachings)
			(Dbob_Bbob_book-teachings)
			(not (PDbob_PBbob_not_book-teachings))
			(not (PDbob_PBalice_not_book-teachings))
			(PBbob_book-teachings)
			(not (PBbob_not_book-teachings))
			(not (Bbob_not_book-teachings))
		)
	)
	 (:action adopt-belief_cindy_l1
	    :parameters ()
	    :precondition (and
			(leader_cindy)
			(at_cindy_l1)
			(book-at_l1)
		)
	    :effect (and
			(Dcindy_Bbob_book-teachings)
			(Dcindy_Bcindy_book-teachings)
			(not (Bcindy_not_book-teachings))
			(not (PDcindy_PBalice_not_book-teachings))
			(PBcindy_book-teachings)
			(not (PBcindy_not_book-teachings))
			(not (PDcindy_PBbob_not_book-teachings))
			(Bcindy_book-teachings)
			(Dcindy_Balice_book-teachings)
			(not (PDcindy_PBcindy_not_book-teachings))
		)
	)
	 (:action adopt-belief_cindy_l2
	    :parameters ()
	    :precondition (and
			(leader_cindy)
			(at_cindy_l2)
			(book-at_l2)
		)
	    :effect (and
			(Dcindy_Bbob_book-teachings)
			(Dcindy_Bcindy_book-teachings)
			(not (Bcindy_not_book-teachings))
			(not (PDcindy_PBalice_not_book-teachings))
			(PBcindy_book-teachings)
			(not (PBcindy_not_book-teachings))
			(not (PDcindy_PBbob_not_book-teachings))
			(Bcindy_book-teachings)
			(Dcindy_Balice_book-teachings)
			(not (PDcindy_PBcindy_not_book-teachings))
		)
	)
	 (:action move_alice_l1_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l1))
			(not (not_at_alice_l1))
			(not_at_alice_l1)
		)
	)
	 (:action move_alice_l1_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(not (at_alice_l1))
			(at_alice_l2)
			(not_at_alice_l1)
			(not (not_at_alice_l2))
		)
	)
	 (:action move_alice_l2_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not_at_alice_l2)
			(not (at_alice_l2))
			(not (not_at_alice_l1))
		)
	)
	 (:action move_alice_l2_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(not_at_alice_l2)
			(at_alice_l2)
			(not (at_alice_l2))
			(not (not_at_alice_l2))
		)
	)
	 (:action move_bob_l1_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l1))
			(not (not_at_bob_l1))
			(not_at_bob_l1)
		)
	)
	 (:action move_bob_l1_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(not (at_bob_l1))
			(at_bob_l2)
			(not_at_bob_l1)
			(not (not_at_bob_l2))
		)
	)
	 (:action move_bob_l2_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (not_at_bob_l1))
			(not_at_bob_l2)
			(not (at_bob_l2))
		)
	)
	 (:action move_bob_l2_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(not_at_bob_l2)
			(at_bob_l2)
			(not (at_bob_l2))
			(not (not_at_bob_l2))
		)
	)
	 (:action move_cindy_l1_l1
	    :parameters ()
	    :precondition (and
			(at_cindy_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(not_at_cindy_l1)
			(at_cindy_l1)
			(not (not_at_cindy_l1))
			(not (at_cindy_l1))
		)
	)
	 (:action move_cindy_l1_l2
	    :parameters ()
	    :precondition (and
			(at_cindy_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_cindy_l2)
			(not_at_cindy_l1)
			(not (not_at_cindy_l2))
			(not (at_cindy_l1))
		)
	)
	 (:action move_cindy_l2_l1
	    :parameters ()
	    :precondition (and
			(at_cindy_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(not_at_cindy_l2)
			(not (at_cindy_l2))
			(at_cindy_l1)
			(not (not_at_cindy_l1))
		)
	)
	 (:action move_cindy_l2_l2
	    :parameters ()
	    :precondition (and
			(at_cindy_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(not_at_cindy_l2)
			(at_cindy_l2)
			(not (at_cindy_l2))
			(not (not_at_cindy_l2))
		)
	)
	 (:action proselytize_alice_alice_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(Balice_book-teachings)
			(Dalice_Balice_book-teachings)
		)
	    :effect (and
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (not_follower_alice_alice)))
			(Balice_Balice_book-teachings)
			(when (and (not (skeptical_alice_alice)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (not (skeptical_alice_alice)) (PBalice_book-teachings)) (follower_alice_alice))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (not (Balice_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (PBalice_book-teachings))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (not (PBalice_book-teachings)))
			(when (and (follower_alice_alice)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(not (PBalice_PBalice_not_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (not_follower_alice_alice)))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_alice_alice))) (not (Balice_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (Balice_not_book-teachings))
			(when (and (not (skeptical_alice_alice)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (not (not_skeptical_alice_alice))) (not (PBalice_book-teachings)))
		)
	)
	 (:action proselytize_alice_alice_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(Balice_book-teachings)
			(Dalice_Balice_book-teachings)
		)
	    :effect (and
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (not_follower_alice_alice)))
			(Balice_Balice_book-teachings)
			(when (and (not (skeptical_alice_alice)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (not (skeptical_alice_alice)) (PBalice_book-teachings)) (follower_alice_alice))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (not (Balice_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (PBalice_book-teachings))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (not (PBalice_book-teachings)))
			(when (and (follower_alice_alice)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(not (PBalice_PBalice_not_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_alice))) (not (not_follower_alice_alice)))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_alice))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_alice_alice))) (not (Balice_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_alice))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_alice)) (Balice_not_book-teachings))
			(when (and (not (skeptical_alice_alice)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (not (not_skeptical_alice_alice))) (not (PBalice_book-teachings)))
		)
	)
	 (:action proselytize_alice_bob_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(Balice_book-teachings)
			(Dalice_Bbob_book-teachings)
			(at_bob_l1)
		)
	    :effect (and
			(when (and (skeptical_bob_alice)) (not (Bbob_book-teachings)))
			(when (and (not (skeptical_bob_alice)) (PBbob_book-teachings)) (follower_bob_alice))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (not_follower_bob_alice)))
			(when (and (not (skeptical_bob_alice)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_alice)) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (PBbob_book-teachings))
			(not (PBbob_PBalice_not_book-teachings))
			(Bbob_Balice_book-teachings)
			(when (and (follower_bob_alice)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (not (not_skeptical_bob_alice))) (not (Bbob_book-teachings)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_alice)) (Bbob_not_book-teachings))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (not (not_skeptical_bob_alice))) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (not_follower_bob_alice)))
			(when (and (skeptical_bob_alice)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (not (skeptical_bob_alice)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (PBbob_not_book-teachings)))
		)
	)
	 (:action proselytize_alice_bob_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(Balice_book-teachings)
			(Dalice_Bbob_book-teachings)
			(at_bob_l2)
		)
	    :effect (and
			(when (and (skeptical_bob_alice)) (not (Bbob_book-teachings)))
			(when (and (not (skeptical_bob_alice)) (PBbob_book-teachings)) (follower_bob_alice))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (not_follower_bob_alice)))
			(when (and (not (skeptical_bob_alice)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_alice)) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (PBbob_book-teachings))
			(not (PBbob_PBalice_not_book-teachings))
			(Bbob_Balice_book-teachings)
			(when (and (follower_bob_alice)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (not (not_skeptical_bob_alice))) (not (Bbob_book-teachings)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_alice)) (Bbob_not_book-teachings))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (Bbob_not_book-teachings)))
			(when (and (not (not_skeptical_bob_alice))) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_alice))) (not (not_follower_bob_alice)))
			(when (and (skeptical_bob_alice)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (not (skeptical_bob_alice)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_alice))) (not (PBbob_not_book-teachings)))
		)
	)
	 (:action proselytize_alice_cindy_l1
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(Balice_book-teachings)
			(Dalice_Bcindy_book-teachings)
			(at_cindy_l1)
		)
	    :effect (and
			(not (PBcindy_PBalice_not_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(Bcindy_Balice_book-teachings)
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (PBcindy_book-teachings))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (PBcindy_not_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_book-teachings)) (follower_cindy_alice))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (not_follower_cindy_alice)))
			(when (and (not (not_skeptical_cindy_alice))) (not (Bcindy_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (skeptical_cindy_alice)) (not (Bcindy_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (skeptical_cindy_alice)) (Bcindy_not_book-teachings))
			(when (and (skeptical_cindy_alice)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_alice))) (not (PBcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (PBcindy_not_book-teachings)))
			(when (and (skeptical_cindy_alice)) (not (PBcindy_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (not_follower_cindy_alice)))
			(when (and (follower_cindy_alice)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
		)
	)
	 (:action proselytize_alice_cindy_l2
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(Balice_book-teachings)
			(Dalice_Bcindy_book-teachings)
			(at_cindy_l2)
		)
	    :effect (and
			(not (PBcindy_PBalice_not_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(Bcindy_Balice_book-teachings)
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (PBcindy_book-teachings))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (PBcindy_not_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_book-teachings)) (follower_cindy_alice))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (not_follower_cindy_alice)))
			(when (and (not (not_skeptical_cindy_alice))) (not (Bcindy_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (skeptical_cindy_alice)) (not (Bcindy_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_alice))) (not (Bcindy_not_book-teachings)))
			(when (and (skeptical_cindy_alice)) (Bcindy_not_book-teachings))
			(when (and (skeptical_cindy_alice)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_alice))) (not (PBcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (PBcindy_not_book-teachings)))
			(when (and (skeptical_cindy_alice)) (not (PBcindy_book-teachings)))
			(when (and (not (skeptical_cindy_alice)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_alice))) (not (not_follower_cindy_alice)))
			(when (and (follower_cindy_alice)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
		)
	)
	 (:action proselytize_bob_alice_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(Bbob_book-teachings)
			(Dbob_Balice_book-teachings)
			(at_alice_l1)
		)
	    :effect (and
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (not (Balice_book-teachings)))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_bob)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_alice_bob))) (not (Balice_book-teachings)))
			(when (and (skeptical_alice_bob)) (Balice_not_book-teachings))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (not_follower_alice_bob)))
			(when (and (not (not_skeptical_alice_bob))) (not (PBalice_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (not_follower_alice_bob)))
			(when (and (not (skeptical_alice_bob)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (not (skeptical_alice_bob)) (PBalice_book-teachings)) (follower_alice_bob))
			(Balice_Bbob_book-teachings)
			(when (and (follower_alice_bob)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (PBalice_book-teachings))
			(not (PBalice_PBbob_not_book-teachings))
		)
	)
	 (:action proselytize_bob_alice_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(Bbob_book-teachings)
			(Dbob_Balice_book-teachings)
			(at_alice_l2)
		)
	    :effect (and
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (not (Balice_book-teachings)))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (PBalice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_bob)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_bob))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_bob)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_alice_bob))) (not (Balice_book-teachings)))
			(when (and (skeptical_alice_bob)) (Balice_not_book-teachings))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_bob))) (not (not_follower_alice_bob)))
			(when (and (not (not_skeptical_alice_bob))) (not (PBalice_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (not (not_follower_alice_bob)))
			(when (and (not (skeptical_alice_bob)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (not (skeptical_alice_bob)) (PBalice_book-teachings)) (follower_alice_bob))
			(Balice_Bbob_book-teachings)
			(when (and (follower_alice_bob)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_bob))) (PBalice_book-teachings))
			(not (PBalice_PBbob_not_book-teachings))
		)
	)
	 (:action proselytize_bob_bob_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(Bbob_book-teachings)
			(Dbob_Bbob_book-teachings)
		)
	    :effect (and
			(when (and (skeptical_bob_bob)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (skeptical_bob_bob)) (Bbob_not_book-teachings))
			(when (and (follower_bob_bob)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (not_follower_bob_bob)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (not_follower_bob_bob)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (not (skeptical_bob_bob)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (not (skeptical_bob_bob)) (PBbob_book-teachings)) (follower_bob_bob))
			(Bbob_Bbob_book-teachings)
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (PBbob_book-teachings))
			(when (and (not (not_skeptical_bob_bob))) (not (Bbob_book-teachings)))
			(when (and (skeptical_bob_bob)) (not (Bbob_book-teachings)))
			(when (and (not (skeptical_bob_bob)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(not (PBbob_PBbob_not_book-teachings))
			(when (and (not (not_skeptical_bob_bob))) (not (PBbob_book-teachings)))
			(when (and (skeptical_bob_bob)) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (PBbob_not_book-teachings)))
		)
	)
	 (:action proselytize_bob_bob_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(Bbob_book-teachings)
			(Dbob_Bbob_book-teachings)
		)
	    :effect (and
			(when (and (skeptical_bob_bob)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (skeptical_bob_bob)) (Bbob_not_book-teachings))
			(when (and (follower_bob_bob)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (not_follower_bob_bob)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (not_follower_bob_bob)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (not (skeptical_bob_bob)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (not (skeptical_bob_bob)) (PBbob_book-teachings)) (follower_bob_bob))
			(Bbob_Bbob_book-teachings)
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (PBbob_book-teachings))
			(when (and (not (not_skeptical_bob_bob))) (not (Bbob_book-teachings)))
			(when (and (skeptical_bob_bob)) (not (Bbob_book-teachings)))
			(when (and (not (skeptical_bob_bob)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(not (PBbob_PBbob_not_book-teachings))
			(when (and (not (not_skeptical_bob_bob))) (not (PBbob_book-teachings)))
			(when (and (skeptical_bob_bob)) (not (PBbob_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_bob))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_bob))) (not (PBbob_not_book-teachings)))
		)
	)
	 (:action proselytize_bob_cindy_l1
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(Bbob_book-teachings)
			(Dbob_Bcindy_book-teachings)
			(at_cindy_l1)
		)
	    :effect (and
			(when (and (not (skeptical_cindy_bob)) (PBcindy_book-teachings)) (follower_cindy_bob))
			(when (and (skeptical_cindy_bob)) (Bcindy_not_book-teachings))
			(when (and (not (skeptical_cindy_bob)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (not_follower_cindy_bob)))
			(when (and (not (skeptical_cindy_bob)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (skeptical_cindy_bob)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (skeptical_cindy_bob)) (not (PBcindy_book-teachings)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (follower_cindy_bob)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
			(not (PBcindy_PBbob_not_book-teachings))
			(Bcindy_Bbob_book-teachings)
			(when (and (not (not_skeptical_cindy_bob))) (not (Bcindy_book-teachings)))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (PBcindy_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (PBcindy_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_bob))) (not (PBcindy_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (PBcindy_not_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (not_follower_cindy_bob)))
			(when (and (skeptical_cindy_bob)) (not (Bcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
		)
	)
	 (:action proselytize_bob_cindy_l2
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(Bbob_book-teachings)
			(Dbob_Bcindy_book-teachings)
			(at_cindy_l2)
		)
	    :effect (and
			(when (and (not (skeptical_cindy_bob)) (PBcindy_book-teachings)) (follower_cindy_bob))
			(when (and (skeptical_cindy_bob)) (Bcindy_not_book-teachings))
			(when (and (not (skeptical_cindy_bob)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (not_follower_cindy_bob)))
			(when (and (not (skeptical_cindy_bob)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (skeptical_cindy_bob)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (skeptical_cindy_bob)) (not (PBcindy_book-teachings)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (follower_cindy_bob)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
			(not (PBcindy_PBbob_not_book-teachings))
			(Bcindy_Bbob_book-teachings)
			(when (and (not (not_skeptical_cindy_bob))) (not (Bcindy_book-teachings)))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (PBcindy_book-teachings))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (PBcindy_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_bob))) (not (PBcindy_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_bob))) (not (PBcindy_not_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (not_follower_cindy_bob)))
			(when (and (skeptical_cindy_bob)) (not (Bcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_bob))) (not (Bcindy_not_book-teachings)))
		)
	)
	 (:action proselytize_cindy_alice_l1
	    :parameters ()
	    :precondition (and
			(at_cindy_l1)
			(Bcindy_book-teachings)
			(Dcindy_Balice_book-teachings)
			(at_alice_l1)
		)
	    :effect (and
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (not_follower_alice_cindy)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (not_follower_alice_cindy)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (PBalice_book-teachings))
			(when (and (skeptical_alice_cindy)) (Balice_not_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_cindy)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (PBalice_not_book-teachings)))
			(Balice_Bcindy_book-teachings)
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (PBalice_not_book-teachings)))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (not (not_skeptical_alice_cindy))) (not (Balice_book-teachings)))
			(not (PBalice_PBcindy_not_book-teachings))
			(when (and (not (not_skeptical_alice_cindy))) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (skeptical_alice_cindy)) (not (Balice_book-teachings)))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (follower_alice_cindy)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(when (and (skeptical_alice_cindy)) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_book-teachings)) (follower_alice_cindy))
		)
	)
	 (:action proselytize_cindy_alice_l2
	    :parameters ()
	    :precondition (and
			(at_cindy_l2)
			(Bcindy_book-teachings)
			(Dcindy_Balice_book-teachings)
			(at_alice_l2)
		)
	    :effect (and
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (not_follower_alice_cindy)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (not_follower_alice_cindy)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_book-teachings)) (Balice_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (PBalice_book-teachings))
			(when (and (skeptical_alice_cindy)) (Balice_not_book-teachings))
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (skeptical_alice_cindy)) (and (Dalice_Bbob_not_book-teachings) (Dalice_Balice_not_book-teachings) (Dalice_Bcindy_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (not (Balice_not_book-teachings)) (not (skeptical_alice_cindy))) (not (PBalice_not_book-teachings)))
			(Balice_Bcindy_book-teachings)
			(when (and (PBalice_book-teachings) (not (skeptical_alice_cindy))) (not (PBalice_not_book-teachings)))
			(when (and (not (Balice_book-teachings)) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (not (not_skeptical_alice_cindy))) (not (Balice_book-teachings)))
			(not (PBalice_PBcindy_not_book-teachings))
			(when (and (not (not_skeptical_alice_cindy))) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_not_book-teachings)) (PBalice_book-teachings))
			(when (and (skeptical_alice_cindy)) (not (Balice_book-teachings)))
			(when (and (PBalice_not_book-teachings) (not (skeptical_alice_cindy))) (not (Balice_not_book-teachings)))
			(when (and (follower_alice_cindy)) (and (Balice_book-teachings) (Dalice_Bcindy_book-teachings) (Dalice_Balice_book-teachings) (Dalice_Bbob_book-teachings)))
			(when (and (skeptical_alice_cindy)) (not (PBalice_book-teachings)))
			(when (and (not (skeptical_alice_cindy)) (PBalice_book-teachings)) (follower_alice_cindy))
		)
	)
	 (:action proselytize_cindy_bob_l1
	    :parameters ()
	    :precondition (and
			(at_cindy_l1)
			(Bcindy_book-teachings)
			(Dcindy_Bbob_book-teachings)
			(at_bob_l1)
		)
	    :effect (and
			(when (and (skeptical_bob_cindy)) (not (PBbob_book-teachings)))
			(not (PBbob_PBcindy_not_book-teachings))
			(when (and (not (not_skeptical_bob_cindy))) (not (PBbob_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (not_follower_bob_cindy)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (not_follower_bob_cindy)))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_cindy)) (Bbob_not_book-teachings))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (PBbob_book-teachings))
			(when (and (not (skeptical_bob_cindy)) (PBbob_book-teachings)) (follower_bob_cindy))
			(when (and (not (skeptical_bob_cindy)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (skeptical_bob_cindy)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(Bbob_Bcindy_book-teachings)
			(when (and (not (skeptical_bob_cindy)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(when (and (skeptical_bob_cindy)) (not (Bbob_book-teachings)))
			(when (and (follower_bob_cindy)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (not (not_skeptical_bob_cindy))) (not (Bbob_book-teachings)))
		)
	)
	 (:action proselytize_cindy_bob_l2
	    :parameters ()
	    :precondition (and
			(at_cindy_l2)
			(Bcindy_book-teachings)
			(Dcindy_Bbob_book-teachings)
			(at_bob_l2)
		)
	    :effect (and
			(when (and (skeptical_bob_cindy)) (not (PBbob_book-teachings)))
			(not (PBbob_PBcindy_not_book-teachings))
			(when (and (not (not_skeptical_bob_cindy))) (not (PBbob_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (not_follower_bob_cindy)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (not_follower_bob_cindy)))
			(when (and (PBbob_not_book-teachings) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (skeptical_bob_cindy)) (Bbob_not_book-teachings))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (PBbob_book-teachings))
			(when (and (not (skeptical_bob_cindy)) (PBbob_book-teachings)) (follower_bob_cindy))
			(when (and (not (skeptical_bob_cindy)) (PBbob_book-teachings)) (Bbob_book-teachings))
			(when (and (skeptical_bob_cindy)) (and (Dbob_Balice_not_book-teachings) (Dbob_Bcindy_not_book-teachings) (Dbob_Bbob_not_book-teachings)))
			(when (and (PBbob_book-teachings) (not (skeptical_bob_cindy))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_not_book-teachings)) (not (skeptical_bob_cindy))) (not (PBbob_not_book-teachings)))
			(when (and (not (Bbob_book-teachings)) (not (skeptical_bob_cindy))) (not (Bbob_not_book-teachings)))
			(Bbob_Bcindy_book-teachings)
			(when (and (not (skeptical_bob_cindy)) (PBbob_not_book-teachings)) (PBbob_book-teachings))
			(when (and (skeptical_bob_cindy)) (not (Bbob_book-teachings)))
			(when (and (follower_bob_cindy)) (and (Bbob_book-teachings) (Dbob_Bbob_book-teachings) (Dbob_Bcindy_book-teachings) (Dbob_Balice_book-teachings)))
			(when (and (not (not_skeptical_bob_cindy))) (not (Bbob_book-teachings)))
		)
	)
	 (:action proselytize_cindy_cindy_l1
	    :parameters ()
	    :precondition (and
			(at_cindy_l1)
			(Bcindy_book-teachings)
			(Dcindy_Bcindy_book-teachings)
		)
	    :effect (and
			(when (and (skeptical_cindy_cindy)) (not (Bcindy_book-teachings)))
			(when (and (skeptical_cindy_cindy)) (Bcindy_not_book-teachings))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_book-teachings)) (follower_cindy_cindy))
			(when (and (skeptical_cindy_cindy)) (not (PBcindy_book-teachings)))
			(when (and (not (not_skeptical_cindy_cindy))) (not (PBcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (not_follower_cindy_cindy)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (PBcindy_not_book-teachings)))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (PBcindy_book-teachings))
			(Bcindy_Bcindy_book-teachings)
			(when (and (follower_cindy_cindy)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (not_follower_cindy_cindy)))
			(when (and (skeptical_cindy_cindy)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (PBcindy_not_book-teachings)))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_cindy))) (not (Bcindy_book-teachings)))
			(not (PBcindy_PBcindy_not_book-teachings))
		)
	)
	 (:action proselytize_cindy_cindy_l2
	    :parameters ()
	    :precondition (and
			(at_cindy_l2)
			(Bcindy_book-teachings)
			(Dcindy_Bcindy_book-teachings)
		)
	    :effect (and
			(when (and (skeptical_cindy_cindy)) (not (Bcindy_book-teachings)))
			(when (and (skeptical_cindy_cindy)) (Bcindy_not_book-teachings))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_book-teachings)) (follower_cindy_cindy))
			(when (and (skeptical_cindy_cindy)) (not (PBcindy_book-teachings)))
			(when (and (not (not_skeptical_cindy_cindy))) (not (PBcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (not_follower_cindy_cindy)))
			(when (and (PBcindy_not_book-teachings) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (PBcindy_not_book-teachings)))
			(when (and (not (Bcindy_book-teachings)) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (PBcindy_book-teachings))
			(Bcindy_Bcindy_book-teachings)
			(when (and (follower_cindy_cindy)) (and (Bcindy_book-teachings) (Dcindy_Bbob_book-teachings) (Dcindy_Balice_book-teachings) (Dcindy_Bcindy_book-teachings)))
			(when (and (not (Bcindy_not_book-teachings)) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (not_follower_cindy_cindy)))
			(when (and (skeptical_cindy_cindy)) (and (Dcindy_Balice_not_book-teachings) (Dcindy_Bcindy_not_book-teachings) (Dcindy_Bbob_not_book-teachings)))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (PBcindy_not_book-teachings)))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_not_book-teachings)) (PBcindy_book-teachings))
			(when (and (not (skeptical_cindy_cindy)) (PBcindy_book-teachings)) (Bcindy_book-teachings))
			(when (and (PBcindy_book-teachings) (not (skeptical_cindy_cindy))) (not (Bcindy_not_book-teachings)))
			(when (and (not (not_skeptical_cindy_cindy))) (not (Bcindy_book-teachings)))
			(not (PBcindy_PBcindy_not_book-teachings))
		)
	)
)