(define (domain grapevine)
	(:requirements :typing)
	(:agents alice bob)
	(:types
	    agent loc
	)
	(:predicates
		(connected_l1_l1)
		(at_alice_l2)
		(at_bob_l2)
		(at_bob_l1)
		(connected_l2_l2)
		(connected_l1_l2)
		(secret_bob)
		(connected_l2_l1)
		(at_alice_l1)
		(secret_alice)
		(DES_alice_secret_bob)
		(DES_bob_secret_bob)
		(PBEL_alice_secret_bob)
		(PBEL_bob_secret_bob)
		(PDES_alice_secret_bob)
		(PDES_bob_secret_bob)
		(BEL_alice_secret_bob)
		(BEL_bob_secret_bob)
		(PDES_alice_not_secret_bob)
		(PDES_bob_not_secret_bob)
		(BEL_alice_not_secret_bob)
		(BEL_bob_not_secret_bob)
		(DES_alice_not_secret_bob)
		(DES_bob_not_secret_bob)
		(PBEL_alice_not_secret_bob)
		(PBEL_bob_not_secret_bob)
		(DES_alice_secret_alice)
		(DES_bob_secret_alice)
		(PBEL_alice_secret_alice)
		(PBEL_bob_secret_alice)
		(PDES_alice_secret_alice)
		(PDES_bob_secret_alice)
		(BEL_alice_secret_alice)
		(BEL_bob_secret_alice)
		(PDES_alice_not_secret_alice)
		(PDES_bob_not_secret_alice)
		(BEL_alice_not_secret_alice)
		(BEL_bob_not_secret_alice)
		(DES_alice_not_secret_alice)
		(DES_bob_not_secret_alice)
		(PBEL_alice_not_secret_alice)
		(PBEL_bob_not_secret_alice)
		(DES_alice_DES_bob_secret_bob)
		(DES_bob_DES_alice_secret_bob)
		(DES_alice_PBEL_alice_secret_bob)
		(DES_alice_PBEL_bob_secret_bob)
		(DES_bob_PBEL_alice_secret_bob)
		(DES_bob_PBEL_bob_secret_bob)
		(DES_alice_PDES_bob_secret_bob)
		(DES_bob_PDES_alice_secret_bob)
		(DES_alice_BEL_alice_secret_bob)
		(DES_alice_BEL_bob_secret_bob)
		(DES_bob_BEL_alice_secret_bob)
		(DES_bob_BEL_bob_secret_bob)
		(PBEL_alice_DES_alice_secret_bob)
		(PBEL_alice_DES_bob_secret_bob)
		(PBEL_bob_DES_alice_secret_bob)
		(PBEL_bob_DES_bob_secret_bob)
		(PBEL_alice_PBEL_bob_secret_bob)
		(PBEL_bob_PBEL_alice_secret_bob)
		(PBEL_alice_PDES_alice_secret_bob)
		(PBEL_alice_PDES_bob_secret_bob)
		(PBEL_bob_PDES_alice_secret_bob)
		(PBEL_bob_PDES_bob_secret_bob)
		(PBEL_alice_BEL_bob_secret_bob)
		(PBEL_bob_BEL_alice_secret_bob)
		(PDES_alice_DES_bob_secret_bob)
		(PDES_bob_DES_alice_secret_bob)
		(PDES_alice_PBEL_alice_secret_bob)
		(PDES_alice_PBEL_bob_secret_bob)
		(PDES_bob_PBEL_alice_secret_bob)
		(PDES_bob_PBEL_bob_secret_bob)
		(PDES_alice_PDES_bob_secret_bob)
		(PDES_bob_PDES_alice_secret_bob)
		(PDES_alice_BEL_alice_secret_bob)
		(PDES_alice_BEL_bob_secret_bob)
		(PDES_bob_BEL_alice_secret_bob)
		(PDES_bob_BEL_bob_secret_bob)
		(BEL_alice_DES_alice_secret_bob)
		(BEL_alice_DES_bob_secret_bob)
		(BEL_bob_DES_alice_secret_bob)
		(BEL_bob_DES_bob_secret_bob)
		(BEL_alice_PBEL_bob_secret_bob)
		(BEL_bob_PBEL_alice_secret_bob)
		(BEL_alice_PDES_alice_secret_bob)
		(BEL_alice_PDES_bob_secret_bob)
		(BEL_bob_PDES_alice_secret_bob)
		(BEL_bob_PDES_bob_secret_bob)
		(BEL_alice_BEL_bob_secret_bob)
		(BEL_bob_BEL_alice_secret_bob)
		(PDES_alice_PDES_bob_not_secret_bob)
		(PDES_bob_PDES_alice_not_secret_bob)
		(PDES_alice_BEL_alice_not_secret_bob)
		(PDES_alice_BEL_bob_not_secret_bob)
		(PDES_bob_BEL_alice_not_secret_bob)
		(PDES_bob_BEL_bob_not_secret_bob)
		(PDES_alice_DES_bob_not_secret_bob)
		(PDES_bob_DES_alice_not_secret_bob)
		(PDES_alice_PBEL_alice_not_secret_bob)
		(PDES_alice_PBEL_bob_not_secret_bob)
		(PDES_bob_PBEL_alice_not_secret_bob)
		(PDES_bob_PBEL_bob_not_secret_bob)
		(BEL_alice_PDES_alice_not_secret_bob)
		(BEL_alice_PDES_bob_not_secret_bob)
		(BEL_bob_PDES_alice_not_secret_bob)
		(BEL_bob_PDES_bob_not_secret_bob)
		(BEL_alice_BEL_bob_not_secret_bob)
		(BEL_bob_BEL_alice_not_secret_bob)
		(BEL_alice_DES_alice_not_secret_bob)
		(BEL_alice_DES_bob_not_secret_bob)
		(BEL_bob_DES_alice_not_secret_bob)
		(BEL_bob_DES_bob_not_secret_bob)
		(BEL_alice_PBEL_bob_not_secret_bob)
		(BEL_bob_PBEL_alice_not_secret_bob)
		(DES_alice_PDES_bob_not_secret_bob)
		(DES_bob_PDES_alice_not_secret_bob)
		(DES_alice_BEL_alice_not_secret_bob)
		(DES_alice_BEL_bob_not_secret_bob)
		(DES_bob_BEL_alice_not_secret_bob)
		(DES_bob_BEL_bob_not_secret_bob)
		(DES_alice_DES_bob_not_secret_bob)
		(DES_bob_DES_alice_not_secret_bob)
		(DES_alice_PBEL_alice_not_secret_bob)
		(DES_alice_PBEL_bob_not_secret_bob)
		(DES_bob_PBEL_alice_not_secret_bob)
		(DES_bob_PBEL_bob_not_secret_bob)
		(PBEL_alice_PDES_alice_not_secret_bob)
		(PBEL_alice_PDES_bob_not_secret_bob)
		(PBEL_bob_PDES_alice_not_secret_bob)
		(PBEL_bob_PDES_bob_not_secret_bob)
		(PBEL_alice_BEL_bob_not_secret_bob)
		(PBEL_bob_BEL_alice_not_secret_bob)
		(PBEL_alice_DES_alice_not_secret_bob)
		(PBEL_alice_DES_bob_not_secret_bob)
		(PBEL_bob_DES_alice_not_secret_bob)
		(PBEL_bob_DES_bob_not_secret_bob)
		(PBEL_alice_PBEL_bob_not_secret_bob)
		(PBEL_bob_PBEL_alice_not_secret_bob)
		(DES_alice_DES_bob_secret_alice)
		(DES_bob_DES_alice_secret_alice)
		(DES_alice_PBEL_alice_secret_alice)
		(DES_alice_PBEL_bob_secret_alice)
		(DES_bob_PBEL_alice_secret_alice)
		(DES_bob_PBEL_bob_secret_alice)
		(DES_alice_PDES_bob_secret_alice)
		(DES_bob_PDES_alice_secret_alice)
		(DES_alice_BEL_alice_secret_alice)
		(DES_alice_BEL_bob_secret_alice)
		(DES_bob_BEL_alice_secret_alice)
		(DES_bob_BEL_bob_secret_alice)
		(PBEL_alice_DES_alice_secret_alice)
		(PBEL_alice_DES_bob_secret_alice)
		(PBEL_bob_DES_alice_secret_alice)
		(PBEL_bob_DES_bob_secret_alice)
		(PBEL_alice_PBEL_bob_secret_alice)
		(PBEL_bob_PBEL_alice_secret_alice)
		(PBEL_alice_PDES_alice_secret_alice)
		(PBEL_alice_PDES_bob_secret_alice)
		(PBEL_bob_PDES_alice_secret_alice)
		(PBEL_bob_PDES_bob_secret_alice)
		(PBEL_alice_BEL_bob_secret_alice)
		(PBEL_bob_BEL_alice_secret_alice)
		(PDES_alice_DES_bob_secret_alice)
		(PDES_bob_DES_alice_secret_alice)
		(PDES_alice_PBEL_alice_secret_alice)
		(PDES_alice_PBEL_bob_secret_alice)
		(PDES_bob_PBEL_alice_secret_alice)
		(PDES_bob_PBEL_bob_secret_alice)
		(PDES_alice_PDES_bob_secret_alice)
		(PDES_bob_PDES_alice_secret_alice)
		(PDES_alice_BEL_alice_secret_alice)
		(PDES_alice_BEL_bob_secret_alice)
		(PDES_bob_BEL_alice_secret_alice)
		(PDES_bob_BEL_bob_secret_alice)
		(BEL_alice_DES_alice_secret_alice)
		(BEL_alice_DES_bob_secret_alice)
		(BEL_bob_DES_alice_secret_alice)
		(BEL_bob_DES_bob_secret_alice)
		(BEL_alice_PBEL_bob_secret_alice)
		(BEL_bob_PBEL_alice_secret_alice)
		(BEL_alice_PDES_alice_secret_alice)
		(BEL_alice_PDES_bob_secret_alice)
		(BEL_bob_PDES_alice_secret_alice)
		(BEL_bob_PDES_bob_secret_alice)
		(BEL_alice_BEL_bob_secret_alice)
		(BEL_bob_BEL_alice_secret_alice)
		(PDES_alice_PDES_bob_not_secret_alice)
		(PDES_bob_PDES_alice_not_secret_alice)
		(PDES_alice_BEL_alice_not_secret_alice)
		(PDES_alice_BEL_bob_not_secret_alice)
		(PDES_bob_BEL_alice_not_secret_alice)
		(PDES_bob_BEL_bob_not_secret_alice)
		(PDES_alice_DES_bob_not_secret_alice)
		(PDES_bob_DES_alice_not_secret_alice)
		(PDES_alice_PBEL_alice_not_secret_alice)
		(PDES_alice_PBEL_bob_not_secret_alice)
		(PDES_bob_PBEL_alice_not_secret_alice)
		(PDES_bob_PBEL_bob_not_secret_alice)
		(BEL_alice_PDES_alice_not_secret_alice)
		(BEL_alice_PDES_bob_not_secret_alice)
		(BEL_bob_PDES_alice_not_secret_alice)
		(BEL_bob_PDES_bob_not_secret_alice)
		(BEL_alice_BEL_bob_not_secret_alice)
		(BEL_bob_BEL_alice_not_secret_alice)
		(BEL_alice_DES_alice_not_secret_alice)
		(BEL_alice_DES_bob_not_secret_alice)
		(BEL_bob_DES_alice_not_secret_alice)
		(BEL_bob_DES_bob_not_secret_alice)
		(BEL_alice_PBEL_bob_not_secret_alice)
		(BEL_bob_PBEL_alice_not_secret_alice)
		(DES_alice_PDES_bob_not_secret_alice)
		(DES_bob_PDES_alice_not_secret_alice)
		(DES_alice_BEL_alice_not_secret_alice)
		(DES_alice_BEL_bob_not_secret_alice)
		(DES_bob_BEL_alice_not_secret_alice)
		(DES_bob_BEL_bob_not_secret_alice)
		(DES_alice_DES_bob_not_secret_alice)
		(DES_bob_DES_alice_not_secret_alice)
		(DES_alice_PBEL_alice_not_secret_alice)
		(DES_alice_PBEL_bob_not_secret_alice)
		(DES_bob_PBEL_alice_not_secret_alice)
		(DES_bob_PBEL_bob_not_secret_alice)
		(PBEL_alice_PDES_alice_not_secret_alice)
		(PBEL_alice_PDES_bob_not_secret_alice)
		(PBEL_bob_PDES_alice_not_secret_alice)
		(PBEL_bob_PDES_bob_not_secret_alice)
		(PBEL_alice_BEL_bob_not_secret_alice)
		(PBEL_bob_BEL_alice_not_secret_alice)
		(PBEL_alice_DES_alice_not_secret_alice)
		(PBEL_alice_DES_bob_not_secret_alice)
		(PBEL_bob_DES_alice_not_secret_alice)
		(PBEL_bob_DES_bob_not_secret_alice)
		(PBEL_alice_PBEL_bob_not_secret_alice)
		(PBEL_bob_PBEL_alice_not_secret_alice)
	)
	(:action move_alice_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l2))
		)
	)
	 (:action move_alice_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l2))
		)
	)
	 (:action move_bob_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l2))
		)
	)
	 (:action move_bob_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l2))
		)
	)
	 (:action share_alice_alice_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(39caa284) / parent(8d41bcb0)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(adc142b0) / parent(8d41bcb0)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(59ef884a) / parent(39caa284)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(8d3bfec4) / parent(10f6fece)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(1070683e) / parent(10f6fece)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(6ce39a3d) / parent(10f6fece)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(47f4e4a3) / parent(8d3bfec4)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(ff12ce43) / parent(8d3bfec4)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(a4a124aa) / parent(1070683e)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(71277a0c) / parent(6ce39a3d)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(54d22495) / parent(47f4e4a3)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(86ad6296) / parent(ff12ce43)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(9c1f4578) / parent(a4a124aa)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(53e5afd0) / parent(54d22495)
		)
	)
	 (:action share_alice_alice_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(b0af5a3a) / parent(4bf93ab4)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(de543978) / parent(4bf93ab4)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(127a474e) / parent(b0af5a3a)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(54cf1250) / parent(ae256053)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(2432d443) / parent(ae256053)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(0d6fc3de) / parent(ae256053)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(98728cae) / parent(54cf1250)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(798bd9f8) / parent(54cf1250)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(d5ad4e1f) / parent(2432d443)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(ac1cbd5d) / parent(0d6fc3de)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(25cc0d32) / parent(98728cae)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(9712cd7a) / parent(798bd9f8)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(64dbfc2f) / parent(d5ad4e1f)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(74fb51e7) / parent(25cc0d32)
		)
	)
	 (:action share_alice_bob_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(5c2b75b3) / parent(fcad4d41)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(f61a942a) / parent(fcad4d41)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(e4854564) / parent(5c2b75b3)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(b6436c7a) / parent(58363e62)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(ebb8c521) / parent(58363e62)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(58d00706) / parent(58363e62)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(20e4b56c) / parent(b6436c7a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(4e1b2051) / parent(b6436c7a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(3d011775) / parent(ebb8c521)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(43aa54e5) / parent(58d00706)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(c7c68c11) / parent(20e4b56c)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(55c0975a) / parent(4e1b2051)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(962c7c69) / parent(3d011775)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(5945d3a4) / parent(c7c68c11)
		)
	)
	 (:action share_alice_bob_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(97dffc86) / parent(271faf38)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(63b3b747) / parent(271faf38)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(3cc3f474) / parent(97dffc86)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(95049ad5) / parent(a6bb14f1)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(a1b8b886) / parent(a6bb14f1)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(d24aba93) / parent(a6bb14f1)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(8a5b6c53) / parent(95049ad5)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(92100335) / parent(95049ad5)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(c8746e7f) / parent(a1b8b886)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(826d1fad) / parent(d24aba93)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(1349b08d) / parent(8a5b6c53)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(b6aa9571) / parent(92100335)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(c98696ee) / parent(c8746e7f)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(ff9f77d3) / parent(1349b08d)
		)
	)
	 (:action share_bob_alice_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(39caa284) / parent(8d41bcb0)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(adc142b0) / parent(8d41bcb0)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(59ef884a) / parent(39caa284)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(8d3bfec4) / parent(10f6fece)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(1070683e) / parent(10f6fece)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(6ce39a3d) / parent(10f6fece)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(47f4e4a3) / parent(8d3bfec4)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(ff12ce43) / parent(8d3bfec4)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(a4a124aa) / parent(1070683e)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(71277a0c) / parent(6ce39a3d)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(54d22495) / parent(47f4e4a3)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(86ad6296) / parent(ff12ce43)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(9c1f4578) / parent(a4a124aa)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(53e5afd0) / parent(54d22495)
		)
	)
	 (:action share_bob_alice_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(b0af5a3a) / parent(4bf93ab4)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(de543978) / parent(4bf93ab4)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(127a474e) / parent(b0af5a3a)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(54cf1250) / parent(ae256053)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(2432d443) / parent(ae256053)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(0d6fc3de) / parent(ae256053)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(98728cae) / parent(54cf1250)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(798bd9f8) / parent(54cf1250)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(d5ad4e1f) / parent(2432d443)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(ac1cbd5d) / parent(0d6fc3de)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(25cc0d32) / parent(98728cae)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(9712cd7a) / parent(798bd9f8)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(64dbfc2f) / parent(d5ad4e1f)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(74fb51e7) / parent(25cc0d32)
		)
	)
	 (:action share_bob_bob_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(5c2b75b3) / parent(fcad4d41)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(f61a942a) / parent(fcad4d41)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(e4854564) / parent(5c2b75b3)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(b6436c7a) / parent(58363e62)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(ebb8c521) / parent(58363e62)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(58d00706) / parent(58363e62)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(20e4b56c) / parent(b6436c7a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(4e1b2051) / parent(b6436c7a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(3d011775) / parent(ebb8c521)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(43aa54e5) / parent(58d00706)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(c7c68c11) / parent(20e4b56c)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(55c0975a) / parent(4e1b2051)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(962c7c69) / parent(3d011775)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(5945d3a4) / parent(c7c68c11)
		)
	)
	 (:action share_bob_bob_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(97dffc86) / parent(271faf38)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(63b3b747) / parent(271faf38)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(3cc3f474) / parent(97dffc86)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(95049ad5) / parent(a6bb14f1)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(a1b8b886) / parent(a6bb14f1)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(d24aba93) / parent(a6bb14f1)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(8a5b6c53) / parent(95049ad5)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(92100335) / parent(95049ad5)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(c8746e7f) / parent(a1b8b886)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(826d1fad) / parent(d24aba93)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(1349b08d) / parent(8a5b6c53)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(b6aa9571) / parent(92100335)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(c98696ee) / parent(c8746e7f)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(ff9f77d3) / parent(1349b08d)
		)
	)
)