(define (domain grapevine)
	(:requirements :typing)
	(:agents alice bob)
	(:types
	    agent loc
	)
	(:predicates
		(at_bob_l1)
		(connected_l1_l2)
		(at_bob_l2)
		(connected_l2_l1)
		(connected_l2_l2)
		(secret_bob)
		(connected_l1_l1)
		(secret_alice)
		(at_alice_l2)
		(at_alice_l1)
	)
	(:action move_alice_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l2))
		)
	)
	 (:action move_alice_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l2))
		)
	)
	 (:action move_bob_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l2))
		)
	)
	 (:action move_bob_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l2))
		)
	)
	 (:action share_alice_alice_l1
	    :derive-condition (at_alice_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
		)
	)
	 (:action share_alice_alice_l2
	    :derive-condition (at_alice_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
		)
	)
	 (:action share_alice_bob_l1
	    :derive-condition (at_alice_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
		)
	)
	 (:action share_alice_bob_l2
	    :derive-condition (at_alice_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
		)
	)
	 (:action share_bob_alice_l1
	    :derive-condition (at_alice_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
		)
	)
	 (:action share_bob_alice_l2
	    :derive-condition (at_alice_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_alice)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_alice))))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_alice)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_alice))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_alice))))
		)
	)
	 (:action share_bob_bob_l1
	    :derive-condition (at_alice_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_alice_l1)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (at_alice_l1) (at_bob_l1) (at_alice_l1)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_alice_l1) (not (PBEL_alice_not (at_bob_l1))) (not (PBEL_alice_not (at_alice_l1))) (not (BEL_alice_not (at_alice_l1)))) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
		)
	)
	 (:action share_bob_bob_l2
	    :derive-condition (at_alice_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_secret_bob)))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob))))
			(when (and (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (not (BEL_alice_not (at_alice_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_not_secret_bob))))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_BEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (BEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (PBEL_alice_PBEL_bob_secret_bob)))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_PBEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (PBEL_alice_BEL_bob_not_secret_bob))))
			(when (and (at_bob_l2) (at_alice_l2) (at_alice_l2) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
			(when (and (not (PBEL_alice_not (at_bob_l2))) (not (PBEL_alice_not (at_alice_l2))) (not (BEL_alice_not (at_alice_l2))) (at_alice_l2)) (and (not (BEL_alice_BEL_bob_not_secret_bob))))
		)
	)
)