(define (domain grapevine)
	(:requirements :typing)
	(:agents alice bob)
	(:types
	    agent loc
	)
	(:predicates
		(at_bob_l2)
		(at_bob_l1)
		(connected_l1_l1)
		(at_alice_l1)
		(connected_l1_l2)
		(at_alice_l2)
		(secret_alice)
		(connected_l2_l2)
		(connected_l2_l1)
		(secret_bob)
	)
	(:action move_alice_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l1))
		)
	)
	 (:action move_alice_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_alice_l1)
			(not (at_alice_l2))
		)
	)
	 (:action move_alice_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_alice_l2)
			(not (at_alice_l2))
		)
	)
	 (:action move_bob_l1_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l1_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(connected_l1_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l1))
		)
	)
	 (:action move_bob_l2_l1
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l1)
		)
	    :effect (and
			(at_bob_l1)
			(not (at_bob_l2))
		)
	)
	 (:action move_bob_l2_l2
	    :derive-condition always
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(connected_l2_l2)
		)
	    :effect (and
			(at_bob_l2)
			(not (at_bob_l2))
		)
	)
	 (:action share_alice_alice_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(7fc54301) / parent(8cae4364)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(b9bcab48) / parent(8cae4364)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(857c9fc7) / parent(7fc54301)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(4b28c965) / parent(c9abe7fe)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(643bdf60) / parent(c9abe7fe)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(de06b055) / parent(c9abe7fe)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(4ef2c3eb) / parent(4b28c965)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(361e9e50) / parent(4b28c965)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(945d5fbf) / parent(643bdf60)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(2be5d475) / parent(de06b055)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(ebf28350) / parent(4ef2c3eb)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(90366fd0) / parent(361e9e50)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(789a0b70) / parent(945d5fbf)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(811346d0) / parent(ebf28350)
		)
	)
	 (:action share_alice_alice_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(697648d4) / parent(58da3dec)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(9f65597f) / parent(58da3dec)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(62e66623) / parent(697648d4)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(84592417) / parent(16d51879)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(3254e7e0) / parent(16d51879)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(aadbabd3) / parent(16d51879)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(36e311ed) / parent(84592417)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(55b28596) / parent(84592417)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(fbd91b89) / parent(3254e7e0)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(9439970a) / parent(aadbabd3)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(71ff8dee) / parent(36e311ed)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(7a5ff15d) / parent(55b28596)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(d1fb6b6b) / parent(fbd91b89)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(eb49b04a) / parent(71ff8dee)
		)
	)
	 (:action share_alice_bob_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_alice_l1)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(f9fd0d7b) / parent(ba2ac2f4)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(0a8f6357) / parent(ba2ac2f4)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(564a82e7) / parent(f9fd0d7b)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(fafd1751) / parent(d3b4cca7)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(a081fb55) / parent(d3b4cca7)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(5eadfed2) / parent(d3b4cca7)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(ac38838a) / parent(fafd1751)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(7d431200) / parent(fafd1751)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(f2d8f841) / parent(a081fb55)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(a3e7f14d) / parent(5eadfed2)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(5e7b1b24) / parent(ac38838a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(6f6a633c) / parent(7d431200)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(8476c1d8) / parent(f2d8f841)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(f36cde13) / parent(5e7b1b24)
		)
	)
	 (:action share_alice_bob_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_alice_l2)
			(BEL_alice_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(62e4a477) / parent(59e17008)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(73ddf81a) / parent(59e17008)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(b2060e72) / parent(62e4a477)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(7ef9c645) / parent(522c3004)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(109d19f4) / parent(522c3004)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(ea0d708c) / parent(522c3004)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(6a7d34b7) / parent(7ef9c645)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(b611f1cf) / parent(7ef9c645)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(67647284) / parent(109d19f4)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(217b87ae) / parent(ea0d708c)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(d277a682) / parent(6a7d34b7)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(f50322cf) / parent(b611f1cf)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(90724f28) / parent(67647284)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(07696aca) / parent(d277a682)
		)
	)
	 (:action share_bob_alice_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(7fc54301) / parent(8cae4364)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(b9bcab48) / parent(8cae4364)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(857c9fc7) / parent(7fc54301)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(4b28c965) / parent(c9abe7fe)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(643bdf60) / parent(c9abe7fe)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(de06b055) / parent(c9abe7fe)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(4ef2c3eb) / parent(4b28c965)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(361e9e50) / parent(4b28c965)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(945d5fbf) / parent(643bdf60)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(2be5d475) / parent(de06b055)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(ebf28350) / parent(4ef2c3eb)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(90366fd0) / parent(361e9e50)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(789a0b70) / parent(945d5fbf)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(811346d0) / parent(ebf28350)
		)
	)
	 (:action share_bob_alice_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_alice)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_alice)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_alice)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_alice)))); negation-removal id(697648d4) / parent(58da3dec)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_alice))); kd45closure__belief id(9f65597f) / parent(58da3dec)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_alice)))); kd45-un-closure__belief id(62e66623) / parent(697648d4)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_alice)))); negation-removal id(84592417) / parent(16d51879)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_alice))); kd45closure__belief id(3254e7e0) / parent(16d51879)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_alice))); mutual-awareness-pos__belief id(aadbabd3) / parent(16d51879)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_alice)))); kd45-un-closure__belief id(36e311ed) / parent(84592417)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_alice))); mutual-awareness-neg__belief id(55b28596) / parent(84592417)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_alice))); mutual-awareness-pos__belief id(fbd91b89) / parent(3254e7e0)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(9439970a) / parent(aadbabd3)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_alice))); mutual-awareness-neg__belief id(71ff8dee) / parent(36e311ed)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_alice)))); negation-removal id(7a5ff15d) / parent(55b28596)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(d1fb6b6b) / parent(fbd91b89)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_alice)))); negation-removal id(eb49b04a) / parent(71ff8dee)
		)
	)
	 (:action share_bob_bob_l1
	    :derive-condition (at_bob_l1)
	    :parameters ()
	    :precondition (and
			(at_bob_l1)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l1)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l1)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l1)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(f9fd0d7b) / parent(ba2ac2f4)
			(when (and (at_bob_l1)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(0a8f6357) / parent(ba2ac2f4)
			(when (and (at_bob_l1)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(564a82e7) / parent(f9fd0d7b)
			(when (and (at_alice_l1)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(fafd1751) / parent(d3b4cca7)
			(when (and (at_alice_l1)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(a081fb55) / parent(d3b4cca7)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(5eadfed2) / parent(d3b4cca7)
			(when (and (at_alice_l1)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(ac38838a) / parent(fafd1751)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(7d431200) / parent(fafd1751)
			(when (and (at_alice_l1) (at_bob_l1)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(f2d8f841) / parent(a081fb55)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(a3e7f14d) / parent(5eadfed2)
			(when (and (at_alice_l1) (at_bob_l1)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(5e7b1b24) / parent(ac38838a)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(6f6a633c) / parent(7d431200)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(8476c1d8) / parent(f2d8f841)
			(when (and (at_alice_l1) (at_bob_l1)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(f36cde13) / parent(5e7b1b24)
		)
	)
	 (:action share_bob_bob_l2
	    :derive-condition (at_bob_l2)
	    :parameters ()
	    :precondition (and
			(at_bob_l2)
			(BEL_bob_secret_bob)
		)
	    :effect (and
			(when (and (at_bob_l2)) (and (BEL_bob_secret_bob)))
			(when (and (at_alice_l2)) (and (BEL_alice_secret_bob)))
			(when (and (at_bob_l2)) (and (not (PBEL_bob_not_secret_bob)))); negation-removal id(62e4a477) / parent(59e17008)
			(when (and (at_bob_l2)) (and (PBEL_bob_secret_bob))); kd45closure__belief id(73ddf81a) / parent(59e17008)
			(when (and (at_bob_l2)) (and (not (BEL_bob_not_secret_bob)))); kd45-un-closure__belief id(b2060e72) / parent(62e4a477)
			(when (and (at_alice_l2)) (and (not (PBEL_alice_not_secret_bob)))); negation-removal id(7ef9c645) / parent(522c3004)
			(when (and (at_alice_l2)) (and (PBEL_alice_secret_bob))); kd45closure__belief id(109d19f4) / parent(522c3004)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_BEL_alice_secret_bob))); mutual-awareness-pos__belief id(ea0d708c) / parent(522c3004)
			(when (and (at_alice_l2)) (and (not (BEL_alice_not_secret_bob)))); kd45-un-closure__belief id(6a7d34b7) / parent(7ef9c645)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_BEL_alice_secret_bob))); mutual-awareness-neg__belief id(b611f1cf) / parent(7ef9c645)
			(when (and (at_alice_l2) (at_bob_l2)) (and (BEL_bob_PBEL_alice_secret_bob))); mutual-awareness-pos__belief id(67647284) / parent(109d19f4)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(217b87ae) / parent(ea0d708c)
			(when (and (at_alice_l2) (at_bob_l2)) (and (PBEL_bob_PBEL_alice_secret_bob))); mutual-awareness-neg__belief id(d277a682) / parent(6a7d34b7)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_PBEL_alice_not_secret_bob)))); negation-removal id(f50322cf) / parent(b611f1cf)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (PBEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(90724f28) / parent(67647284)
			(when (and (at_alice_l2) (at_bob_l2)) (and (not (BEL_bob_BEL_alice_not_secret_bob)))); negation-removal id(07696aca) / parent(d277a682)
		)
	)
)