(define (problem depth_2_agents_2)
	(:domain grapevine)
	(:requirements :typing)
	(:objects l1 l2 - loc)
	(:init 
		(connected_l2_l1)
		[BEL, alice](secret_alice)
		(connected_l1_l2)
		[BEL, bob](secret_bob)
		(at_alice_l1)
		(at_bob_l2)
	)
	(:goal 
		[ITN, alice](move_alice_l1_l2)
	)
)