QMRK: "?"
LSQB: "["
RSQB: "]"
GREATER_OP: ">"
LESSER_OP: "<"
LPAR : "("
RPAR : ")"
BELIEF: "bel"
DESIRE: "des"
INTENTION: "itn"
DISDAIN: "dsd"
LOVE: "lov"
COMMA: ","
EXC: "!"
RML_NAME: "rml"
NAME: /[a-zA-Z][a-zA-Z0-9-_]*/
COMMENT: /;[^\n]*/

start: atomic_formula_term_rml

var: QMRK NAME

modl_term: BELIEF | DESIRE | INTENTION | DISDAIN | LOVE

modl: LSQB modl_term COMMA var RSQB | LESSER_OP modl_term COMMA var GREATER_OP

terminal_rml:

atomic_formula_term_rml: [EXC] modl* [LSQB] LPAR [EXC] RML_NAME RPAR [RSQB]


%ignore /\s+/
%ignore COMMENT
%import common.WS
%ignore WS